<?php

class home_banner_slideshow {

    protected $_group = 5;
    protected $_category = 81;
    protected $_active = 1;
    protected $_front_template;
    protected $_translator;
    protected $_view;
    protected $postValue;
    protected $_vacationrentals_db;

    public function __construct($view) {
        $this->_front_template = Zend_Registry::get('front_template');
        $this->_view = $view;
        $this->_translator = Zend_Registry::get('translator');
        $frontController = Zend_Controller_Front::getInstance();
        $this->postValue = $frontController->getRequest()->getPost();
        $this->_banner_db = new News_Model_DbTable_Page();
    }

    public function class_body() {
//        $cdnExt = 'http://static.busana.com/';
//        echo $this->_view->headScript()->setFile('application/layouts/scripts/' . $this->_front_template['theme_folder'] . '/vendor/scripts/js/unslider.min.js');
//        echo $this->_view->headScript()->setFile($cdnExt.'js/unslider.min.js', 'text/javascript');
//        echo $this->_view->headLink()->setStylesheet('application/layouts/scripts/' . $this->_front_template['theme_folder'] . '/css/unslider.css');
        //$search_params['filter']['filters'][0] = array('field' => 'group_id', 'operator' => 'eq', 'value' => $this->_group);
        //$search_params['filter']['logic'] = ($search_params['filter']['logic']) ? $search_params['filter']['logic'] : 'and';
        //$search_params['filter']['filters'][1] = array('field' => 'category_id', 'operator' => 'eq', 'value' => $this->_category);
        //$list_info = $this->_banner_db->getListInfo($this->_active, $search_params, false) ;
        ?>

        <div class="banner">
            <ul>
<!--                <li class="lazy" data-src="http://www.pembantu.com/application/layouts/scripts/responsive_default/images/banner-1.jpg">
                    <div class="container">
                        <h1><?php echo $this->_translator->translator('banner_dialog_1', '', '', $this->_front_template['theme_folder']); ?>
                            <p><?php echo $this->_translator->translator('banner_slogan_1', '', '', $this->_front_template['theme_folder']); ?></p>
                        </h1>
                    </div>
                </li>
                <li class="lazy" data-src="http://www.pembantu.com/application/layouts/scripts/responsive_default/images/banner-2.jpg">
                    <div class="container">
                        <h1><?php echo $this->_translator->translator('banner_dialog_2', '', '', $this->_front_template['theme_folder']); ?>
                            <p><?php echo $this->_translator->translator('banner_slogan_2', '', '', $this->_front_template['theme_folder']); ?></p>
                        </h1>
                    </div>
                </li>-->
                <li class="lazy background-size-100 no-repeat" data-src="data/frontImages/banner-homepage.jpg">
                    <div class="container">
                        <h1><?php echo $this->_translator->translator('banner_dialog_3', '', '', $this->_front_template['theme_folder']); ?>
                            <p><?php echo $this->_translator->translator('banner_slogan_3', '', '', $this->_front_template['theme_folder']); ?></p>
                        </h1>
                    </div>
                </li>
            </ul>
        </div>

        <?php
    }

}

try {
    $home_banner_slideshow_class = new home_banner_slideshow($this);
    $home_banner_slideshow_class->class_body();
} catch (Exception $e) {
    echo $e->getMessage();
}
?>