<div class="row">
    <div class="col-md-8">
        <h1 class="bold-30 margin-bottom-12">   
            <?php echo ucwords($property_name); ?>
            <span class="label label-warning x-long">
                <?php echo strtoupper($getPropertyType); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-4">
        <div class="pull-right margin-top-12">
            <span>
                <a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'emails', 'action' => 'friend', 'property_title' => $this->escape($this->view_datas['property_title']), 'form_id' => $this->translator->translator('email_to_friend_form_id')), 'Email-To-Friend/:property_title/:form_id', true); ?>" title="<?php echo $this->translator->translator('common_email_to_friend'); ?>">
                    <i class="fa fa-envelope-o font-18 grey-dark"></i>
                </a>
            </span>
            <span>
                <a href="javascript:void(0);" class="print_btn" rel="0" title="<?php echo $this->translator->translator('common_print'); ?>">
                    <i class="fa fa-print font-18 grey-dark margin-left-4"></i>
                </a>
            </span>            
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-8">
                        <p class="panel-title margin-top-4 font-12">
                            <?php // echo $this->translator->translator('property_front_page_property_description'); ?>
                            <?php
                            if ($this->view_datas['available_added_on']) {
                                echo $this->ProductForm->available_added_on->getAttrib('font_end_label') . ' ' . $property_added_on;
                            }
                            ?>
                        </p>
                    </div>
                    <div class="col-md-4 padding-left-0">
                        <div class="products-vote margin-0 pull-right">
                            <p class="margin-0"><?php echo $this->translator->translator('property_front_page_label_voting'); ?></p>
                            <span><?php $vote->showButton($this->view_datas['id'], $this->escape($this->view_datas['property_name'])); ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="products-slideshow">
                    <?php
                    $property_image_val_arr = explode(',', $this->view_datas['property_image']);
                    if ($this->escape($this->view_datas['property_primary_image'])) {
                        $thumb_image = 'data/frontImages/property/property_image/' . $this->escape($this->view_datas['property_primary_image']);
                    } else {
                        if ($this->escape($this->view_datas['property_image'])) {
                            $thumb_image = 'data/frontImages/property/property_image/' . $this->escape($property_image_val_arr[0]);
                        } else {
                            $thumb_image = 'application/layouts/scripts/' . $front_template['theme_folder'] . '/images/mod_property_img/no_image.png';
                        }
                    }
                    if ($this->group_datas['img_big_width'] && ($this->group_datas['img_big_resize_func'] == 'resizeToWidth' || $this->group_datas['img_big_resize_func'] == 'resize' )) {
                        $width = 'width="' . $this->escape($this->group_datas['img_big_width']) . '"';
                    } else {
                        $width = '';
                    }
                    if ($this->group_datas['img_big_height'] && ( $this->group_datas['img_big_resize_func'] == 'resizeToHeight' || $this->group_datas['img_big_resize_func'] == 'resize' )) {
                        $height = 'height="' . $this->escape($this->group_datas['img_big_height']) . '"';
                    } else {
                        $height = '';
                    }
                    ?>

                    <div id="container">
                        <div id="gallery" class="ad-gallery">
                            <div class="ad-image-wrapper"></div>
                            <div class="ad-controls"></div>
                            <div class="ad-nav">
                                <div class="ad-thumbs">
                                    <ul class="ad-thumb-list" style="min-width:100%;">
                                        <li>
                                            <a href="<?php echo $thumb_image; ?>">
                                                <img src="<?php echo $thumb_image; ?>"  width="70" height="80" title="<?php echo $this->escape($this->propertyForm->property_name->getValue()); ?>" alt="<?php echo $this->escape($this->escape($this->view_datas['house_location']) . ', ' . $state_info['state_name']) . ', ' . $this->escape($country_info['value']); ?>"  class="image0" /></a>
                                            </a>
                                        </li>
                                        <?php
                                        foreach ($property_image_val_arr as $key => $value) {
                                            if ($thumb_image != 'data/frontImages/property/property_image/' . $value) {
                                                ?>
                                                <li> 
                                                    <a href="data/frontImages/property/property_image/<?php echo $value; ?>"> 
                                                        <img src="data/frontImages/property/property_image/<?php echo $value; ?>"  width="70" height="80" title="<?php echo $this->escape($this->propertyForm->property_name->getValue()); ?>" alt="<?php echo $this->escape($this->escape($this->view_datas['house_location']) . ', ' . $state_info['state_name']) . ', ' . $this->escape($country_info['value']); ?>"  class="image0" /></a> 
                                                </li>
                                                <?php
                                            }
                                        }
                                        ?>		
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="switch">
                            <select id="switch-effect">
                                <option value="slide-hori">Slide horizontal</option>
                                <option value="slide-vert">Slide vertical</option>
                                <option value="resize">Shrink/grow</option>
                                <option value="fade">Fade</option>
                                <option value="">None</option>
                            </select>
                            <a href="#" id="toggle-slideshow">Slideshow on/off</a> | <a href="#" id="toggle-description">Description on/off</a>
                        </div>
                    </div>
                </div>
                <div class="btn-group pull-right" role="group" aria-label="...">
                    <button type="button" class="btn btn-default disabled opacity-1">
                        <?php
                        for ($i = 1; $i < $maximum_stars_digit; $i++) {
                            $property_stars = ($i <= $this->escape($this->view_datas['stars'])) ? "<i class='fa fa-star orange-light'></i>" : "<i class='fa fa-star-o grey-dark'></i>";
                            //$property_stars = ($i <= $this->escape($this->view_datas['stars'])) ? "<img src='application/layouts/scripts/" . $front_template['theme_folder'] . "/images/mod_property_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/" . $front_template['theme_folder'] . "/images/mod_property_img/star-inactive.png' border='0'/>";
                            echo $property_stars . '&nbsp;';
                        }
                        ?>
                    </button>
                    <button type="button" class="btn btn-primary btn-default">
                        <?php
                        if (!empty($this->group_datas['review_id'])) {
                            $review_no = (!empty($this->review_datas)) ? htmlentities($this->review_datas['review_no']) : htmlentities('0');
                            ?>
                            <a href="javascript:void(0);" class="white no-decoration" rel="#tabs-5">
                                <?php echo $this->translator->translator('common_review_no', $review_no); ?>
                            </a>
                        <?php } ?>
                    </button>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>                                
                                <a href="<?php echo $this->url(array('module' => 'Review', 'controller' => 'frontend', 'action' => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $this->view_datas['id']), 'Review-Write/:group_id/:item_id', true); ?>">
                                    <?php echo $this->translator->translator('common_write_review'); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">

        <div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
            <ul id="myTabs" class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#preview" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true"><?php echo $this->translator->translator('property_tab_short_desc'); ?></a></li>
                <li role="presentation" class=""><a href="#skill" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false"><?php echo $this->translator->translator('property_tab_skills'); ?></a></li>
                <!--<li role="presentation" class=""><a href="#details" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Detail</a></li>-->
                <li role="presentation" class=""><a href="#agency" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false"><?php echo $this->translator->translator('property_tab_agency'); ?></a></li>
                <!--                <li role="presentation" class="dropdown">
                                    <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false"><span class="caret"></span></a>
                                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="myTabDrop1" id="myTabDrop1-contents">
                                        <li class=""><a href="#dropdown1" role="tab" id="dropdown1-tab" data-toggle="tab" aria-controls="dropdown1" aria-expanded="false">Print</a></li>
                                        <li class=""><a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2" aria-expanded="false">Email ke Teman</a></li>
                                        <li class=""><a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2" aria-expanded="false">Laporkan ke Admin</a></li>
                                    </ul>
                                </li>-->
            </ul>
            <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane fade active in" id="preview" aria-labelledby="home-tab">
                    <p class="normal-13 margin-top-bottom-8">
                        <?php echo $setPropertyDescShort; ?>
                    </p>
                    <ul class="list-group">
                        <?php
                        if (!empty($this->view_datas['feature_bathroom'])) {
                            $getPropertyAge = $this->translator->translator('maid_age') . ' ' . (int) $this->escape($this->view_datas['feature_bathroom']) . ' ' . $this->translator->translator('property_front_page_bathroom');
                            $property_age = strtolower($getPropertyAge);
                            ?>	
                            <li class="list-group-item">
                                <span class="badge icon-placeholder">
                                    <i class="fa fa-heartbeat <?php echo $css_state_age; ?>"></i>
                                </span>
                                <?php echo ucfirst($property_age); ?>
                            </li>
                            <?php
                        }
                        ?>
                        <li class="list-group-item">
                            <span class="badge icon-placeholder">
                                <i class="fa fa-file-text <?php echo $css_state_police; ?>"></i>
                            </span>
                            <?php
                            $getPropertyLetterPolice = $this->escape($this->view_datas['feature_kitchen']);
                            $property_letter_police = str_replace('_', ' ', $getPropertyLetterPolice);
                            echo ucfirst($property_letter_police);
                            ?>
                        </li>
                        <li class="list-group-item">
                            <span class="badge icon-placeholder">
                                <i class="fa fa-file-text-o <?php echo $css_state_doctor; ?>"></i>
                            </span>
                            <?php
                            $search = array('_', 'doctor');
                            $replace = array(' ', 'doctor\'s');
                            $getPropertyLetterDoctor = $this->escape($this->view_datas['feature_garden']);
                            $property_letter_doctor = str_replace($search, $replace, $getPropertyLetterDoctor);
                            echo ucfirst($property_letter_doctor);
                            ?>
                        </li> 
                        <li class="list-group-item">
                            <span class="badge icon-placeholder">
                                <i class="fa fa-bullhorn <?php echo $css_state_refence; ?>"></i>
                            </span>
                            <?php
                            $getPropertyReference = $this->escape($this->view_datas['feature_garage']);
                            $property_reference = str_replace('_', ' ', $getPropertyReference);
                            echo ucfirst($property_reference);
                            ?>
                        </li>
                    </ul>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="skill" aria-labelledby="profile-tab">
                    <div class="clear margin-top-bottom-8"></div>
                    <ul class="list-group">
                        <?php
                        $feature_amenities_arr = explode(',', $this->view_datas['feature_amenities']);
                        if (!empty($feature_amenities_arr[0])) {
                            ?>
                            <?php
                            foreach ($feature_amenities_arr as $key => $value) {
                                echo '
                                    <li class="list-group-item"><span class="badge icon-placeholder">
                                    <i class="fa fa-check-square-o green-light"></i>
                                    </span>' . $this->escape($value) . '</li>';
                            }
                            ?>                     

                        <?php } ?>
                    </ul>
                </div>
                <!--<div role="tabpanel" class="tab-pane fade" id="details" aria-labelledby="profile-tab"></div>-->
                <div role="tabpanel" class="tab-pane fade" id="agency" aria-labelledby="profile-tab">
                    <?php
                    //Checking Membership Package Option
                    if ($packages->checkFormAvailable('Default Info')) {
                        $default_form_id = $forms_db->getFormId('Default Info');
                        $default_form_info['form_id'] = $default_form_id[0]['id'];
                        $default_general_info = $general_db->getAllValues($default_form_id[0]['id']);
                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();
                        if ($default_general_info) {
                            $default_general_info = (!empty($default_general_info[0]) && !empty($default_general_info[0]['id'])) ? $default_general_info : $default_general_info->toArray();
                            $default_form_info = $dynamic_valu_db->getFieldsValueInfo($default_form_info, $default_general_info[0]['id']);
                        } else {
                            $default_form_info = null;
                        }
                    } else {
                        $default_form_info = null;
                    }
                    if ($packages->isPackageFrontend($mem_info['user_id'], $mem_info['role_id'])) {
                        if ($packages->isPackageFrontendField($module, $controller, $action, $mem_info['user_id'], $mem_info['role_id'])) {
                            $package_no = $packages->getPackageFrontendFieldValue($module, $controller, $action, $mem_info['user_id'], $mem_info['role_id']);
                        } else {
                            $package_no = 'Non-aktif';
                        }
                    } else {
                        $package_no = 'Aktif';
                    }

                    if ($package_no == 'Aktif') {
                        if ($hasIdentity) {
                            ?>
                            <div class="content margin-top-bottom-8">
                                <?php
                                if ($this->escape($this->view_datas['property_owner'])) {
                                    $mem_db = new Members_Model_DbTable_MemberList();
                                    $owner_info = (isnot_int($this->view_datas['property_owner'])) ? $this->escape($this->view_datas['property_owner']) : $mem_db->getMemberInfo($this->escape($this->view_datas['property_owner']));
//                                            print_r($owner_info);
                                    $owner_name = (is_array($owner_info)) ? $owner_info['firstName'] . ' ' . $owner_info['lastName'] : $owner_info;
                                    $mem_user_id = (is_array($owner_info)) ? $owner_info['user_id'] : $mem_info['user_id'];
//                                            print_r($mem_user_id);
                                    $mem_user_register_date = (is_array($owner_info)) ? $owner_info['register_date'] : $mem_info['register_date'];
//                                            print_r($mem_user_register_date);
                                    $mem_role_id = (is_array($owner_info)) ? $owner_info['role_id'] : $mem_info['role_id'];

                                    if (is_array($owner_info) && $owner_info['country']) {
                                        include_once 'connect.php';
                                        $kodeNegara = $this->escape($owner_info['country']);
                                        $query = "SELECT * FROM eicra_countries 
                                                WHERE id = '$kodeNegara'";
                                        $result = mysql_query($query) or die("Wah error nih!");
                                        while ($namaKota = mysql_fetch_array($result)) {
                                            $country_name = $namaKota['value'];
                                        }
                                    }

                                    if (is_array($owner_info)) {
                                        $role_db = new Members_Model_DbTable_Role();
                                        $role_info = $role_db->getRoleInfo($owner_info['role_id']);
                                        $owner_info['form_id'] = $role_info['form_id'];
                                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();
                                        $owner_info = $dynamic_valu_db->getFieldsValueInfo($owner_info, $owner_info['user_id']);
                                        foreach ($owner_info as $key => $value) {
                                            $field_name_arr = explode('_', $key);
                                            if (in_array('package', $field_name_arr)) {
                                                $package_info = $packages->getFormAllDatas($value);
                                            }
                                        }
                                    } else {
                                        $mem_user_id = $mem_info['user_id'];
                                        $mem_role_id = $mem_info['role_id'];
                                        $role_db = new Members_Model_DbTable_Role();
                                        $role_info = $role_db->getRoleInfo($mem_role_id);
                                        $mem_info['form_id'] = $role_info['form_id'];
                                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();
                                        $mem_info = $dynamic_valu_db->getFieldsValueInfo($mem_info, $mem_user_id);
                                        foreach ($mem_info as $key => $value) {
                                            $field_name_arr = explode('_', $key);
                                            if (in_array('package', $field_name_arr)) {
                                                $package_info = $packages->getFormAllDatas($value);
                                            }
                                        }
                                    }
                                } else {
                                    $mem_user_id = $mem_info['user_id'];
                                    $mem_role_id = $mem_info['role_id'];
                                    $role_db = new Members_Model_DbTable_Role();
                                    $role_info = $role_db->getRoleInfo($mem_role_id);
                                    $mem_info['form_id'] = $role_info['form_id'];
                                    $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();
                                    $mem_info = $dynamic_valu_db->getFieldsValueInfo($mem_info, $mem_user_id);
                                    foreach ($mem_info as $key => $value) {
                                        $field_name_arr = explode('_', $key);
                                        if (in_array('package', $field_name_arr)) {
                                            $package_info = $packages->getFormAllDatas($value);
                                        }
                                    }
                                }

                                if (is_array($owner_info)) {
                                    if (!empty($owner_info['member_photo'])) {
                                        $owner_forms_info = $forms_db->getFormsInfo($role_info['form_id']);
                                        $member_photo_path = $owner_forms_info['attach_file_path'];
                                        $member_photo = $member_photo_path . '/' . $owner_info['member_photo'];
                                        $member_photo_width = 'width="' . $default_form_info['member_photo_width_default'] . '"';
                                        $member_photo_height = 'height="' . $default_form_info['member_photo_height_default'] . '"';
                                    } else {
                                        if (!empty($default_form_info)) {
                                            $member_photo = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['member_photo_default'];
                                            $member_photo_width = 'width="' . $default_form_info['member_photo_width_default'] . '"';
                                            $member_photo_height = 'height="' . $default_form_info['member_photo_height_default'] . '"';
                                        } else {
                                            $member_photo = 'data/frontImages/property/design_images/no_user_image.png';
                                            $member_photo_width = 'width="75"';
                                            $member_photo_height = 'height="87"';
                                        }
                                    }
                                } else {
                                    if (!empty($default_form_info)) {
                                        $member_photo = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['member_photo_default'];
                                        $member_photo_width = 'width="' . $default_form_info['member_photo_width_default'] . '"';
                                        $member_photo_height = 'height="' . $default_form_info['member_photo_height_default'] . '"';
                                    } else {
                                        $member_photo = 'data/frontImages/property/design_images/no_user_image.png';
                                        $member_photo_width = 'width="75"';
                                        $member_photo_height = 'height="87"';
                                    }
                                }
                                ?>
                                <!--<img src="<?php echo $member_photo; ?>" <?php echo $member_photo_width . ' ' . $member_photo_height; ?> class="avatar" />-->

                                <!--                                        <div>
                                                                            <span class="label"><?php echo $this->translator->translator('property_front_page_label_presented'); ?></span>
                                                                            <br/>
                                                                            <span class="value">
                                <?php
                                if ($this->escape($this->view_datas['property_owner'])) {
                                    echo $this->escape($owner_name);
                                }
                                ?>
                                                                            </span>
                                                                        </div>-->
                                <!--
                                                                        <div>
                                                                            <div class="pkg-img">
                                <?php
                                if ($packages->isPackageFrontendField($module, $controller, $action . '_pic', $mem_user_id, $mem_role_id)) {
                                    $package_pic_info = $packages->getPackageFrontendFieldDetailsValue($module, $controller, $action . '_pic', $mem_user_id, $mem_role_id);
                                    if (!empty($package_pic_info)) {
                                        $forms_info = $forms_db->getFormsInfo($package_pic_info['form_id']);
                                        if (!empty($package_pic_info['field_value'])) {
                                            $package_pic = $this->serverUrl() . $this->baseUrl() . '/' . $forms_info['attach_file_path'] . '/' . $package_pic_info['field_value'];
                                            $package_pic_width = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_pic_width', $mem_user_id, $mem_role_id);
                                            $package_pic_height = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_pic_height', $mem_user_id, $mem_role_id);
                                            $package_pic_width_field = ($package_pic_width) ? 'width="' . $package_pic_width . '"' : '';
                                            $package_pic_height_field = ($package_pic_width) ? 'height="' . $package_pic_height . '"' : '';
                                        } else {
                                            $package_pic = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['property_frontend_details_pic_default'];
                                            $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="' . $default_form_info['property_frontend_details_pic_width_default'] . '"' : '';
                                            $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="' . $default_form_info['property_frontend_details_pic_height_default'] . '"' : '';
                                        }
                                    } else {
                                        $package_pic = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['property_frontend_details_pic_default'];
                                        $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="' . $default_form_info['property_frontend_details_pic_width_default'] . '"' : '';
                                        $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="' . $default_form_info['property_frontend_details_pic_height_default'] . '"' : '';
                                    }
                                } else {
                                    $package_pic = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['property_frontend_details_pic_default'];
                                    $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="' . $default_form_info['property_frontend_details_pic_width_default'] . '"' : '';
                                    $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="' . $default_form_info['property_frontend_details_pic_height_default'] . '"' : '';
                                }
                                if ($package_pic) {
                                    ?>
                                                                                                                                        <img src="<?php echo $package_pic; ?>" width="80px" height="80px" />
                                    <?php
                                }
                                ?>	
                                                                            </div>   
                                                                            <span class="label"><?php
                                if (($package_info[0]['field_value'])) {
                                    echo $this->translator->translator('common_package_name_title');
                                }
                                ?></span><br />
                                                                            <div class="pkg-title"><?php echo $this->escape($package_info[0]['field_value']); ?></div>
                                                                        </div>
                                
                                                                        <hr />-->

                                <?php
                                if ($packages->isPackageFrontendField($module, $controller, $action . '_contact_directly', $mem_user_id, $mem_role_id)) {
                                    $contact_directly = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_contact_directly', $mem_user_id, $mem_role_id);
                                } else {
                                    $contact_directly = 'Tidak';
                                }
                                if ($contact_directly == 'Ya') {
                                    ?>                                   
                                    <?php
                                    if ($packages->isPackageFrontendField($module, $controller, $action . '_certified', $mem_user_id, $mem_role_id)) {
                                        $allow_certified = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_certified', $mem_user_id, $mem_role_id);
                                    } else {
                                        $allow_certified = 'Tidak';
                                    }
                                    if ($packages->isPackageFrontendField($module, $controller, $action . '_allow_logo', $mem_user_id, $mem_role_id)) {
                                        $allow_logo = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_allow_logo', $mem_user_id, $mem_role_id);
                                    } else {
                                        $allow_logo = 'Tidak';
                                    }
                                    ?>
                                    <?php
                                    if ($allow_logo == 'Ya') {
                                        if (is_array($owner_info)) {
                                            if ($owner_info['company_logo']) {
                                                $company_logo_path = $owner_forms_info['attach_file_path'];
                                                $member_photo_paths = 'data/frontImages/attachFiles';
                                                $company_logo = $member_photo_paths . '/' . $owner_info['company_logo'];
                                                $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="' . $default_form_info['company_logo_width_default'] . '"' : '';
                                                $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="' . $default_form_info['company_logo_height_default'] . '"' : '';
                                            } else {
                                                if (!empty($default_form_info)) {
                                                    $company_logo = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['company_logo_default'];
                                                    $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="' . $default_form_info['company_logo_width_default'] . '"' : '';
                                                    $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="' . $default_form_info['company_logo_height_default'] . '"' : '';
                                                } else {
                                                    $company_logo = 'images/frontImages/property/design_images/no_company_logo.gif';
                                                    $company_logo_width = 'width="100"';
                                                    $company_logo_height = 'height="100"';
                                                }
                                            }
                                        } else {
                                            if (!empty($default_form_info)) {
                                                $company_logo = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['company_logo_default'];
                                                $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="' . $default_form_info['company_logo_width_default'] . '"' : '';
                                                $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="' . $default_form_info['company_logo_height_default'] . '"' : '';
                                            } else {
                                                $company_logo = 'images/frontImages/property/design_images/no_company_logo.gif';
                                                $company_logo_width = 'width="100"';
                                                $company_logo_height = 'height="100"';
                                            }
                                        }
                                        ?>
                                        <div class="pull-center margin-bottom-12">
                                            <img src="<?php echo $company_logo; ?>" <?php echo $company_logo_width . ' ' . $company_logo_height; ?> class="company-logo" />
                                        </div>
                                        <?php
                                    }
                                    ?>
                                    <?php
                                    if (is_array($owner_info)) {
                                        ?> 
                                        <div class="panel panel-success">
                                            <!-- Default panel contents -->
                                            <div class="panel-heading"><i class="fa fa-university margin-right-4"></i>Informasi Penyalur</div>

                                            <!-- Table -->
                                            <table class="table">
                                                <tbody>                                                  
                                                    <tr>
                                                        <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_company'); ?></td>
                                                        <td class="value-table">
                                                            <?php
                                                            if ($owner_info['companyName']) {
                                                                echo $this->escape($owner_info['companyName']);
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_address'); ?></td>
                                                        <td class="value-table">
                                                            <?php
                                                            if ($owner_info['address']) {
                                                                echo " " . ucwords($this->escape($owner_info['address']));
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_city'); ?></td>
                                                        <td class="value-table">
                                                            <?php
                                                            if ($owner_info['city']) {
                                                                echo " " . ucwords($this->escape($owner_info['city']));
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_province'); ?></td>
                                                        <td class="value-table">
                                                            <?php
                                                            if ($owner_info['state']) {
                                                                echo " " . ucwords($this->escape($owner_info['state']));
                                                            }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                    if ($owner_info['country']) {
                                                        ?>
                                                        <tr>
                                                            <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_country'); ?></td>
                                                            <td class="value-table"><?php echo $country_name; ?></td>
                                                        </tr>
                                                        <?php
                                                    }
                                                    if ($owner_info['phone']) {
                                                        ?>                                                    
                                                        <tr>
                                                            <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_phone'); ?></td>
                                                            <td class="value-table"><?php echo $this->escape($owner_info['phone']); ?></td>
                                                        </tr>
                                                        <?php
                                                    }
                                                    if ($owner_info['website']) {
                                                        $site_url = 'http://' . $this->escape($owner_info['website']);
                                                        $site_name = $this->escape($owner_info['website']);
                                                        ?> 
                                                        <tr>
                                                            <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_web'); ?></td>
                                                            <td class="value-table">
                                                                <a href="<?php echo $site_url; ?>" title="<?php echo $site_name; ?>" target="_blank" rel="nofollow" class="agent-web">
                                                                    <?php echo property_substract($site_name, 20); ?>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    <?php } ?>
                <!--                                                    <tr>
                                                    <td class="label-table">Label</td>
                                                    <td class="value-table">Value</td>
                                                </tr>-->
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="pull-center margin-top-4">
                                            <span class="btn btn-xs btn-info">
                                                <a href="<?php
                                                if (is_array($owner_info)) {
                                                    echo 'mailto:' . strtolower($this->escape($owner_info['username']));
                                                } else {
                                                    echo 'mailto:' . strtolower($this->escape($this->view_datas['house_email']));
                                                }
                                                ?>" class="white"><?php echo $this->translator->translator('property_front_page_label_email_lang'); ?></a>
                                            </span>
                                            <span class="btn btn-xs btn-primary"><a class="white" href="<?php echo $this->baseUrl() . 'Agent-Property-List/' . $mem_user_id; ?>"><?php echo $this->translator->translator('stock_of_maids'); ?></a></span>
                                        </div>
                                        <!-- /Email -->
                                    <?php } ?>


                                    <?php
                                }
                                ?>
                                <hr/>
                                <!-- Certificate -->
                                <div class="certificate">
                                    <?php
                                    if ($allow_certified == 'Ya') {
                                        if ($packages->isPackageFrontendField($module, $controller, $action . '_pic_certi', $mem_user_id, $mem_role_id)) {
                                            $package_pic_certi_info = $packages->getPackageFrontendFieldDetailsValue($module, $controller, $action . '_pic_certi', $mem_user_id, $mem_role_id);
                                            if (!empty($package_pic_certi_info)) {
                                                $forms_info = $forms_db->getFormsInfo($package_pic_certi_info['form_id']);
                                                if (!empty($package_pic_certi_info['field_value'])) {
                                                    $package_pic_certi = $this->serverUrl() . $this->baseUrl() . '/' . $forms_info['attach_file_path'] . '/' . $package_pic_certi_info['field_value'];
                                                    $package_pic_certi_width = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_pic_certi_width', $mem_user_id, $mem_role_id);
                                                    $package_pic_certi_height = $packages->getPackageFrontendFieldValue($module, $controller, $action . '_pic_certi_height', $mem_user_id, $mem_role_id);
                                                    $package_pic_certi_width_field = ($package_pic_certi_width) ? 'width="' . $package_pic_certi_width . '"' : '';
                                                    $package_pic_certi_height_field = ($package_pic_certi_height) ? 'height="' . $package_pic_certi_height . '"' : '';
                                                } else {
                                                    $package_pic_certi = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['property_frontend_details_pic_certi_default'];
                                                    $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="' . $default_form_info['property_frontend_details_pic_certi_width_default'] . '"' : '';
                                                    $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="' . $default_form_info['property_frontend_details_pic_certi_height_default'] . '"' : '';
                                                }
                                            } else {
                                                $package_pic_certi = $this->serverUrl() . $this->baseUrl() . '/' . $default_form_id[0]['attach_file_path'] . '/' . $default_form_info['property_frontend_details_pic_certi_default'];
                                                $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="' . $default_form_info['property_frontend_details_pic_certi_width_default'] . '"' : '';
                                                $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="' . $default_form_info['property_frontend_details_pic_certi_height_default'] . '"' : '';
                                            }
                                        } else {
                                            $package_pic_certi = null;
                                        }
                                        if ($package_pic_certi) {
                                            ?>
                                            <img src="<?php echo $package_pic_certi; ?>" <?php echo $package_pic_certi_width_field . ' ' . $package_pic_certi_height_field; ?> />

                                            <?php
                                        }
                                    }
                                    ?>
                                    <p><?php
                                        if ($allow_certified == 'Ya') {
                                            echo $this->translator->translator('property_front_page_label_verified');
                                        }
                                        ?></p>
                                </div>
                                <!-- Certificate Up -->

                            </div>
                            <!--Content END UP -->
                            <!--Else Member Condition Start-->
                            <?php
                        } else {
                            ?>
                            <div class="margin-top-bottom-8">
                                <div class="mod-container package-info"><?php echo $this->translator->translator('member_only'); ?></div> 
                                <div class="pull-center">
                                    <span><a href="Register" class="btn btn-xs btn-primary"><?php echo $this->translator->translator('member_only_register'); ?></a></span>
                                    <span><a href="Frontend-Login" class="btn btn-xs btn-success"><?php echo $this->translator->translator('login'); ?></a></span>
                                </div>                                        
                            </div>
                            <?php
                        }
                    }
                    ?>                              

                </div>
                <!--                <div role="tabpanel" class="tab-pane fade" id="dropdown1" aria-labelledby="dropdown1-tab">
                                    <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="dropdown2" aria-labelledby="dropdown2-tab">
                                    <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                                </div>-->
            </div>
        </div>


        <div class="alert products-price">
            <span><?php echo $this->translator->translator('property_front_page_price'); ?></span>
            <span>
                <!-- Number Format-->
                <?php
                $number = $this->price($this->escape($this->view_datas['property_price']));
                echo number_format($number, 0, ',', '.') . '' . $this->translator->translator('property_front_per_month') . '';
                ?>
            </span>
        </div>
        <div class="pull-center margin-bottom-12">
            <?php if ($hasIdentity) { ?>
                <span class="btn btn-success btn-lg">
                    <a href="javascript:void(0);" class="save_property_btn white no-decoration" rel="<?php echo $this->escape($this->view_datas['id']); ?>">
                        <?php echo $this->translator->translator('property_front_page_save_property'); ?>
                    </a>
                </span>
                <?php
            }
            if ($global_conf['payment_system'] == 'On') {
                ?>
                <span class="btn btn-success btn-lg"><a class="white no-decoration" href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'emails', 'action' => 'owner', 'property_title' => $this->escape($this->view_datas['property_title']), 'form_id' => $this->translator->translator('contact_owner_form_id')), 'Contact-Owner/:property_title/:form_id', true); ?>"><?php echo $this->translator->translator('property_front_page_book_btn'); ?></a></span>
                <?php } ?>            
        </div>
    </div>
</div>