            <div class="products-middle-tab">	
                <ul>
                    <li><a href="javascript:void(0);" class="print_btn" rel="0"><?php echo $this->translator->translator('common_print'); ?></a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'emails', 'action' => 'friend', 'property_title' => $this->escape($this->view_datas['property_title']), 'form_id' => $this->translator->translator('email_to_friend_form_id')), 'Email-To-Friend/:property_title/:form_id', true); ?>"><?php echo $this->translator->translator('common_email_to_friend'); ?></a></li>
                </ul>
            </div>