<div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#container-3_details" id="container-3_details-tab" role="tab" data-toggle="tab" aria-controls="container-3_details" aria-expanded="true"><?php echo $getPropertyDetailsTabLabel; ?></a></li>
        <li role="presentation" class=""><a href="#container-3_profile" role="tab" id="container-3_profile-tab" data-toggle="tab" aria-controls="container-3_profile" aria-expanded="false"><?php echo $getPropertyProfileTabLabel; ?><span class="badge margin-left-4 display-inline"><?php echo $property_image_no; ?></span></a></li>
        <li role="presentation" class=""><a href="#container-3_activity" role="tab" id="container-3_activity-tab" data-toggle="tab" aria-controls="container-3_activity" aria-expanded="false"><?php echo $getPropertyActivityTabLabel; ?><span class="badge margin-left-4 display-inline"><?php echo $property_floor_image_no; ?></span></a></li>
        <li role="presentation" class=""><a href="#container-3_area" role="tab" id="container-3_area-tab" data-toggle="tab" aria-controls="container-3_area" aria-expanded="false"><?php echo $getPropertySkillsAreaLabel; ?></a></li>
        <li role="presentation" class=""><a href="#container-3_review" role="tab" id="container-3_review-tab" data-toggle="tab" aria-controls="container-3_review" aria-expanded="false"><?php echo $getPropertyReviewLabel; ?></a></li>        
    </ul>
    <div id="myTabContent" class="tab-content margin-top-bottom-8">
        <div role="tabpanel" class="tab-pane fade active in" id="container-3_details" aria-labelledby="home-tab">
        <?php include_once 'contents/container-3/details.phtml'; ?>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="container-3_profile" aria-labelledby="profile-tab">
            <?php include_once 'contents/container-3/profile.phtml'; ?>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="container-3_activity" aria-labelledby="activity-tab">
            <?php include_once 'contents/container-3/activity.phtml'; ?>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="container-3_area" aria-labelledby="area-tab">
            <?php include_once 'contents/container-3/area.phtml'; ?>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="container-3_review" aria-labelledby="review-tab">
            <?php include_once 'contents/container-3/review.phtml'; ?>
        </div>
    </div>
</div>