<?php
//echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/BookingCalendar/js/jquery.dop.BookingCalendar.js');
//echo $this->headLink()->setStylesheet($this->baseUrl() . '/js/jquery/BookingCalendar/css/jquery.dop.BookingCalendar.css');
echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/gallery/jquery.ad-gallery.js');
echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/raty/js/jquery.raty.js');
echo $this->headLink()->setStylesheet($this->baseUrl() . '/js/jquery/gallery/jquery.ad-gallery.css');
//echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/jquery.scrollTo.js');
