            <?php
            if (!empty($prevProperty) || !empty($nextProperty)) {
                ?>
                <nav>
                    <ul class="pager margin-top-bottom-10">
                        <?php
                        if (!empty($prevProperty)) {
                            ?>
                            <li class="previous">
                                <a href="<?php echo 'Property-details/' . $this->escape($prevProperty['property_title']); ?>"><span aria-hidden="true">&larr;</span><?php echo $this->translator->translator('property_front_page_prev_property'); ?></a>
                            </li>
                            <?php
                        } else {
                            ?>
                            <li class="previous disabled">
                                <a href="#"><span aria-hidden="true">&larr;</span><?php echo $this->translator->translator('property_front_page_prev_property'); ?></a>
                            </li>
                            <?php
                        }
                        if (!empty($nextProperty)) {
                            ?>
                            <li class="next">
                                <a href="<?php echo 'Property-details/' . $this->escape($nextProperty['property_title']); ?>"><?php echo $this->translator->translator('property_front_page_next_property'); ?><span aria-hidden="true">&rarr;</span></a>
                            </li>
                            <?php
                        } else {
                            ?>
                             <li class="next disabled">
                            <a href="#"><?php echo $this->translator->translator('property_front_page_next_property'); ?><span aria-hidden="true">&rarr;</span></a>
                             <li class="next">
                            <?php
                        }
                        ?>                        
                    </ul>
                </nav>
                <?php
            }
            ?>