<?php
$front_template = Zend_Registry::get('front_template');
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance();
$acount_link = 'Members/index/profile';
$my_account_link = ($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">' . $this->translator->translator('header_account', '', '', $front_template['theme_folder']) . '|' . '</a>' : '<a href="">' . '</a>';
$sugnIn_link = ($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">' . $this->translator->translator('header_signout', '', '', $front_template['theme_folder']) . '</a>' : '<a href="Frontend-Login">' . $this->translator->translator('header_signin', '', '', $front_template['theme_folder']) . '</a>';
$sugnIn_link_agency = ($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">' . $this->translator->translator('header_logout', '', '', $front_template['theme_folder']) . '</a>' : '<a href="Sign-In">' . $this->translator->translator('header_login', '', '', $front_template['theme_folder']) . '</a>';
$add_url = $this->baseUrl() . 'Frontend-Login';
$devider = ' |';
$tab_title_recent_title = $this->translator->translator('block_recent_title', '', '', $front_template['theme_folder']);
$tab_title_immediately_available = $this->translator->translator('tab_commercial_title', '', '', $front_template['theme_folder']);
$tab_title_already_available = $this->translator->translator('tab_residential_title', '', '', $front_template['theme_folder']);
$tab_title_inval = $this->translator->translator('tab_pending_title', '', '', $front_template['theme_folder']);
$frontend_maid = $this->translator->translator('frontend_maid', '', '', $front_template['theme_folder']);
$frontend_baby_sitter = $this->translator->translator('frontend_baby_sitter', '', '', $front_template['theme_folder']);
$frontend_nany = $this->translator->translator('frontend_nany', '', '', $front_template['theme_folder']);
$frontend_nurse_elderly = $this->translator->translator('frontend_nurse_elderly', '', '', $front_template['theme_folder']);
$frontend_gardener = $this->translator->translator('frontend_gardener', '', '', $front_template['theme_folder']);
$frontend_driver = $this->translator->translator('frontend_driver', '', '', $front_template['theme_folder']);
?>
<div class="row">
    <div class="col-md-2">
        <a href="pembantu-rumah-tangga" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_maid ?></a>
    </div>
    <div class="col-md-2">
        <a href="baby-sitter" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_baby_sitter ?></a>
    </div>
    <div class="col-md-2">
        <a href="nanny" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_nany ?></a>
    </div>
    <div class="col-md-2">
        <a href="perawat-lansia" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_nurse_elderly ?></a>
    </div>
    <div class="col-md-2">
        <a href="tukang-kebun" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_gardener ?></a>
    </div>
    <div class="col-md-2">
        <a href="sopir" class="btn btn-block btn-default margin-top-bottom-6"><i class="fa fa-caret-down pull-right"></i><?php echo $frontend_driver ?></a>
    </div>
</div>