<?php
$front_template = Zend_Registry::get('front_template');
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance();
$acount_link = 'Members/index/profile';
$my_account_link = ($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">' . $this->translator->translator('header_account', '', '', $front_template['theme_folder']) . '|' . '</a>' : '<a href="">' . '</a>';
$sugnIn_link = ($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">' . $this->translator->translator('header_signout', '', '', $front_template['theme_folder']) . '</a>' : '<a href="Frontend-Login">' . $this->translator->translator('header_signin', '', '', $front_template['theme_folder']) . '</a>';
$sugnIn_link_agency = ($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">' . $this->translator->translator('header_logout', '', '', $front_template['theme_folder']) . '</a>' : '<a href="Sign-In">' . $this->translator->translator('header_login', '', '', $front_template['theme_folder']) . '</a>';
$add_url = $this->baseUrl() . 'Frontend-Login';
$devider = ' |';
?>
<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
    <a class="navmenu-brand" href="#">Menu</a>
    <ul class="nav navmenu-nav">
        <?php echo $this->partial('blocks/menu_header.phtml'); ?>
    </ul>
</nav>
<!--        <nav id="myNavmenu2" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
          <a class="navmenu-brand" href="#">Brand</a>
          <ul class="nav navmenu-nav">
              <li>Test1</li>
              <li>Test2</li>
          </ul>
        </nav>-->
<div class="navbar navbar-default navbar-static-top">
    <button type="button" class="navbar-toggle pull-left margin-left-4" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="#myNavmenuCanvas" data-placement="left">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <h4 class="pull-center panel-title">
        <a href="<?php echo $this->baseUrl; ?>">
            <img class="img-responsive display-inline logo-mobile" src="<?php if ($global_conf['frontend_header_logo']) {
            echo $global_conf['frontend_header_logo'];
        } else { ?>application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/logo-site.png<?php } ?>" alt="<?php echo $this->escape($global_conf['site_title']); ?>" title="<?php echo $this->escape($global_conf['site_title']); ?>" border="0">
        </a>
    </h4>
    <!--    <button type="button" class="navbar-toggle pull-right" data-toggle="offcanvas" data-target="#myNavmenu2" data-canvas="#myNavmenuCanvas2" data-placement="left">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>-->
</div>        

