<?php 

$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance ();
$acount_link = 'Members/index/profile' ;
$my_account_link	=	($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">'.$this->translator->translator('header_account','', '', $front_template['theme_folder']).'|'.'</a>' : '<a href="">'.'</a>';
$sugnIn_link	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_signout','', '', $front_template['theme_folder']).'</a>' : '<a href="Frontend-Login">'.$this->translator->translator('header_signin','', '', $front_template['theme_folder']).'</a>';
$sugnIn_link_agency	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_logout','', '', $front_template['theme_folder']).'</a>' : '<a href="Sign-In">'.$this->translator->translator('header_login','', '', $front_template['theme_folder']).'</a>';
$add_url =  $this->baseUrl().'Frontend-Login';
$devider = ' |';
?>
<nav class="navbar navbar-default navbar-fixed-top green margin-bottom-0">
    
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h4 class="navbar pull-center panel-title">
                    <a href="#" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <img class="img-responsive display-inline logo-mobile" src="<?php if($global_conf['frontend_header_logo']){ echo $global_conf['frontend_header_logo']; }else{ ?>application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/logo-site.png<?php } ?>" alt="<?php echo $this->escape($global_conf['site_title']); ?>" title="<?php echo $this->escape($global_conf['site_title']); ?>" border="0">
                    </a>
                    </h4>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav top-menu">
                        <?php echo $this->partial('blocks/menu_header.phtml'); ?>
                    </ul>  
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>