<?php
$datas_meta = ($this->view_datas) ? $this->view_datas->getCurrentItems() : '';
//print_r($datas_meta);
if (!empty($datas_meta[0]['firstName'])) {
    $this->headMeta()->setName('keywords', $datas_meta[0]['title'] . ' ' . $datas_meta[0]['firstName'] . ' ' . $datas_meta[0]['lastName']);
}
if (!empty($datas_meta[0]['firstName'])) {
    $this->headMeta()->setName('description', $datas_meta[0]['title'] . ' ' . $datas_meta[0]['firstName'] . ' ' . $datas_meta[0]['lastName']);
}
if (!empty($datas_meta[0]['firstName'])) {
    $this->headTitle()->headTitle($datas_meta[0]['title'] . ' ' . $datas_meta[0]['firstName'] . ' ' . $datas_meta[0]['lastName'], 'SET')->setSeparator(' - ')->headTitle($this->translator->translator('property_front_page_agent_metatitle'));
}

echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/table-sorter/jquery.dataTables.js');
echo $this->headScript()->setFile($this->baseUrl() . '/js/jquery/jtruncate/jquery.jtruncate.pack.js');
echo $this->headLink()->setStylesheet($this->baseUrl() . '/css/jqueryCSS/table-sorter/pagination_table.css');
$version = Zend_Registry::get('version');
$front_template = Zend_Registry::get('front_template');
$business_type_db = new Property_Model_DbTable_BusinessType();
$cat_Info = new Property_Model_DbTable_Category();
$mem_db = new Members_Model_DbTable_MemberList();
$state_db = new Property_Model_DbTable_State();
$area_db = new Property_Model_DbTable_Area();
$country_db = new Property_Model_DbTable_Country();
$review_helper = new Review_View_Helper_Review();
$maximum_stars_digit = $this->translator->translator('maximum_stars_digit');
// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline', 'property_page');

$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
$curSymbol = $currency->getSymbol();
$getLabelDownPayment = $this->translator->translator('property_front_page_label_administration_fee');
$getLabelPropertyPrice = $this->translator->translator('property_front_page_price');
$property_type_arr = explode(',', $this->translator->translator('property_front_page_rent_id'));
$auth = Zend_Auth::getInstance();
$hasIdentity = $auth->hasIdentity();

function property_truncate($phrase, $start_words, $max_words) {
    $phrase_array = explode(' ', $phrase);
    if (count($phrase_array) > $max_words && $max_words > 0)
        $phrase = implode(' ', array_slice($phrase_array, $start_words, $max_words)) . '...';
    return $phrase;
}
?>
<div class="mod">
    <div class="property-list-icon view padding-0">
        <i class="pull-left fa fa-user fa-3x"></i>
        <h1 class="padding-top-10 bold-18"><?php echo $this->translator->translator('property_front_page_list') . ' (' . $this->escape($datas_meta[0]['title'] . $datas_meta[0]['companyName']) . ')'; ?></h1>
    </div>
<!--    <div class="social">
         AddThis Button BEGIN 
        <div class="addthis_toolbox addthis_default_style">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
            <a class="addthis_button_tweet"></a>
            <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
            <a class="addthis_counter addthis_pill_style"></a>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4e89660c7edb029a"></script>
         AddThis Button END 
    </div>-->
    <div class="clear"></div>
    <?php
    if ($hasIdentity) {
        ?> 
        <table id="sortTable" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
            <tbody>
                <?php
//                  if (!empty($this->view_datas)) {
                $entries = $this->view_datas;

                //$entries = $this->_request->getParam( "property_owner" );
//                foreach ($entries as $entry) {
                if (!empty($this->view_datas)) {
                    foreach ($this->view_datas as $entry) {
//                        print_r($entry);
                        $statPub = $this->escape($entry['active']);
//                        echo $statPub;
                        if ($statPub == '1') {
                            $property_image_val_arr = explode(',', $entry['property_image']);
                            $property_image_no = (empty($property_image_val_arr[0])) ? '0' : count($property_image_val_arr);
                            if ($this->escape($entry['property_primary_image'])) {
                                $thumb_image = 'data/frontImages/property/property_image/' . $this->escape($entry['property_primary_image']);
                            } else {
                                if ($this->escape($entry['property_image'])) {
                                    $thumb_image = 'data/frontImages/property/property_image/' . $this->escape($property_image_val_arr[0]);
                                } else {
                                    $thumb_image = 'application/layouts/scripts/' . $front_template['theme_folder'] . '/images/mod_property_img/no_image.png';
                                }
                            }
                            if ($entry['file_thumb_width'] && ($entry['file_thumb_resize_func'] == 'resizeToWidth' || $entry['file_thumb_resize_func'] == 'resize')) {
                                $width = 'width="' . $this->escape($entry['file_thumb_width']) . '"';
                            } else {
                                $width = '';
                            }
                            if ($entry['file_thumb_height'] && ($entry['file_thumb_resize_func'] == 'resizeToHeight' || $entry['file_thumb_resize_func'] == 'resize')) {
                                $height = 'height="' . $this->escape($entry['file_thumb_height']) . '"';
                            } else {
                                $height = '';
                            }
                            $featured_class = ($entry['featured'] && $entry['active'] == '1') ? 'products-featured' : '';
                            $active_class = ($entry['active'] == '1' ? 'product-activated' : 'product-featured');
                            $getPropertyName = $this->escape(property_truncate($entry['property_name'], 0, 5));
                            $property_name = strtolower($getPropertyName);
                            $getPropertyReference = $this->escape($entry['feature_garage']);
                            $property_ref_letter = str_replace('_', ' ', $getPropertyReference);
                            $getPropertyLetterDoctor = $this->escape($entry['feature_garden']);
                            $search_doctor = array('_', 'doctor');
                            $replace_doctor = array(' ', 'doctor\'s');
                            $property_doc_letter = str_replace($search_doctor, $replace_doctor, $getPropertyLetterDoctor);
                            $getPropertyLetterPolice = $this->escape($entry['feature_kitchen']);
                            $property_police_letter = str_replace('_', ' ', $getPropertyLetterPolice);
                            $getPropertyAge = $this->escape($entry['feature_bathroom']);
                            $setPropertyAge = $this->translator->translator('maid_age') . ' ' . (int) $getPropertyAge . ' ' . $this->translator->translator('property_front_page_bathroom');
                            $property_age = strtolower($setPropertyAge);
                            $getPropertyExperience = (int) $this->escape($entry['feature_room_no']);
                            $setYearText = 'Tahun';
                            $setExperienceText = 'Pengalaman Kerja ';
                            $setPropertyExperience = $getPropertyExperience . ' ' . $setYearText;
                            $getProperty_desc = $this->escape(strip_tags($entry['property_desc']));
                            $setPropertyDesc = strtolower($getProperty_desc);
                            $property_desc = ucfirst($setPropertyDesc);
                            ?>
                            <?php
                            //Create variable stack from top, do not replace this
                            $css_state_refence = '';
                            $css_state_doctor = '';
                            $css_state_police = '';
                            $css_state_age = '';
                            $css_state_experience = '';
                            $css_style_experience = '';
                            if (strpos($property_ref_letter, 'tersedia') !== false) {
                                $css_state_refence = 'green-light';
                            } else {
                                $css_state_refence = 'grey';
                            }
                            if (strpos($property_doc_letter, 'sehat') !== false) {
                                $css_state_doctor = 'green-light';
                            } else {
                                $css_state_doctor = 'grey';
                            }
                            if (strpos($property_police_letter, 'baik') !== false) {
                                $css_state_police = 'green-light';
                            } else {
                                $css_state_police = 'grey';
                            }
                            switch (!empty($getPropertyExperience)) {
                                case ($getPropertyExperience <= 5):
                                    $css_state_experience = $getPropertyExperience * 20;
                                    $css_style_experience = 'success';
                                    break;
                                case ($getPropertyExperience >= 6 && $getPropertyExperience <= 10):
                                    $css_state_experience = $getPropertyExperience * 10;
                                    $css_style_experience = 'warning';
                                    break;
                                case ($getPropertyExperience >= 11 && $getPropertyExperience <= 20):
                                    $css_state_experience = $getPropertyExperience * 5;
                                    $css_style_experience = 'danger';
                                    break;
                                case ($getPropertyExperience >= 20 && $getPropertyExperience <= 30):
                                    $css_state_experience = $getPropertyExperience * 3.33;
                                    $css_style_experience = 'danger';
                                    break;
                                default :
                                    $css_state_experience = $getPropertyExperience;
                                    $css_style_experience = 'primary';
                            }
                            switch ($getPropertyAge) {
                                case ($getPropertyAge <= 20):
                                    $css_state_age = 'green-light';
                                    break;
                                case ($getPropertyAge >= 21 && $getPropertyAge <= 30):
                                    $css_state_age = 'violet';
                                    break;
                                case ($getPropertyAge >= 31 && $getPropertyAge <= 40);
                                    $css_state_age = 'yellow';
                                    break;
                                case ($getPropertyAge >= 41 && $getPropertyAge <= 50);
                                    $css_state_age = 'red-light';
                                    break;
                                case ($getPropertyAge >= 51 && $getPropertyAge <= 60);
                                    $css_state_age = 'red-dark';
                                    break;
                                default :
                                    $css_state_age = 'grey';
                            }
                            ?>
                            <tr>
                                <td>
                                    <div class="panel panel-success products-list">
                                        <div class="panel-heading">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <span class="title-small"><?php echo $setExperienceText; ?></span>
                                                    <div class="progress margin-0" data-toggle="tooltip" data-placement="left" title="<?php echo $getPropertyExperience . ' ' . $setYearText . ' ' . $setExperienceText; ?>">
                                                        <div class="progress-bar progress-bar-striped progress-bar-<?php echo $css_style_experience; ?> active" role="progressbar" aria-valuenow="<?php echo $css_state_experience; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $css_state_experience; ?>%;">
                                                            <?php echo $setPropertyExperience; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-5">
                                                    <div class="margin-top-6">
                                                        <span class="products-mark">
                                                            <?php
                                                            $type_infos = $business_type_db->getBusinessTypeInfo($entry['property_type']);
                                                            echo $this->translator->translator('property_front_page_property_for');
                                                            ?></span>&nbsp;<span class="products-type"><?php echo $this->escape($type_infos['business_type']); ?></span>
                                                    </div>
                                                </div>
                                                <div class="price-tag">
                                                    <i class="normal right-11">
                                                        <span class="sallary">
                                                            <?php echo $this->translator->translator('property_front_page_price'); ?>
                                                        </span>
                                                        <span>
                                                            <?php
                                                            $getPropertyPrice = $this->price($this->escape($entry['property_price']));
                                                            $propertyPrice = $curSymbol . ' ' . number_format($getPropertyPrice, 0, ',', '.');
                                                            echo $propertyPrice;
                                                            ?>
                                                        </span>
                                                    </i>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-md-8 padding-right-0">
                                                    <div class="img-wrapper">
                                                        <a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>" class="preview" link="<?php echo $thumb_image; ?>" width="350" title="<?php echo $this->escape($entry['property_name']); ?>"><img src="<?php echo $thumb_image; ?>" <?php echo $width; ?> <?php echo $height; ?> border="0" class="thumb"/></a>
                                                        <div class="photo-count-container">
                                                            <div class="photo-count">
                                                                <a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title']), 'tab' => 1), 'Property-details/:property_title/:tab', true); ?>" title="<?php echo $this->translator->translator('property_front_page_click_view_photos'); ?>"><?php echo $this->translator->translator('property_front_page_property_photo_no', $property_image_no); ?></a>
                                                            </div>
                                                        </div>                                            
                                                    </div>
                                                    <h2>
                                                        <a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>" class="preview" title="<?php echo $this->escape($entry['property_name']); ?>" link=""><?php echo ucwords($property_name); ?></a>
                                                    </h2>

                                                    <div class="products-stars">
                                                        <?php
                                                        for ($i = 1; $i < $maximum_stars_digit; $i++) {
                                                            $property_stars = ($i <= $this->escape($entry['stars'])) ? "<img src='application/layouts/scripts/" . $front_template['theme_folder'] . "/images/mod_property_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/" . $front_template['theme_folder'] . "/images/mod_property_img/star-inactive.png' border='0'/>";
                                                            echo $property_stars . '&nbsp;';
                                                        }
                                                        ?>
                                                    </div>

                                                    <div class="products-desc">
                                                        <p><?php echo $this->translator->translator('property_front_page_property_location'); ?></p> <?php
                                                        $states = $state_db->getStateInfo($entry['state_id']);
                                                        $areas = $area_db->getAreaInfo($entry['area_id']);
                                                        echo $this->escape($states['state_name']);
                                                        ?><br />
                                                        <p><?php echo $this->translator->translator('property_front_page_property_country'); ?></p> <?php
                                                        $countries = $country_db->getCountryName($entry['country_id']);
                                                        echo $this->escape($countries['value']);
                                                        ?><br />
                                                        <article class="width-auto">
                                                            <p><?php echo $this->translator->translator('property_front_page_property_desc'); ?></p>
                                                            <?php echo $property_desc; ?>
                                                        </article>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <ul class="list-group">
                                                        <li class="list-group-item">
                                                            <span class="badge icon-placeholder">
                                                                <i class="fa fa-heartbeat <?php echo $css_state_age; ?>"></i>
                                                            </span>
                                                            <?php echo ucfirst($property_age); ?>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <span class="badge icon-placeholder">
                                                                <i class="fa fa-file-text <?php echo $css_state_police; ?>"></i>
                                                            </span>
                                                            <?php
                                                            echo ucfirst($property_police_letter);
                                                            ?>
                                                        </li>
                                                        <li class="list-group-item">
                                                            <span class="badge icon-placeholder">
                                                                <i class="fa fa-file-text-o <?php echo $css_state_doctor; ?>"></i>
                                                            </span>
                                                            <?php
                                                            echo ucfirst($property_doc_letter);
                                                            ?>
                                                        </li> 
                                                        <li class="list-group-item">
                                                            <span class="badge icon-placeholder">
                                                                <i class="fa fa-bullhorn <?php echo $css_state_refence; ?>"></i>
                                                            </span>
                                                            <?php
                                                            echo ucfirst($property_ref_letter);
                                                            ?>
                                                        </li>
                                                    </ul>                                    
                                                </div>  
                                            </div>
                                        </div>
                                        <div class="panel-footer <?php echo $featured_class; ?>">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="products-vote">
                                                        <p><?php echo $this->translator->translator('property_front_page_label_voting'); ?></p>
                                                        <span><?php $vote->showButton($entry['id'], $this->escape($entry['property_name'])); ?></span>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="pull-right">
                                                        <a class="btn btn-warning font-13 no-decoration white" href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'emails', 'action' => 'owner', 'property_title' => $this->escape($entry['property_title']), 'form_id' => $this->translator->translator('contact_owner_form_id')), 'Contact-Owner/:property_title/:form_id', true); ?>"><?php echo $this->translator->translator('property_front_page_property_book'); ?></a>
                                                        <!--<span class="btn btn-success products-details-btn"><a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>"><?php echo $this->translator->translator('property_front_page_property_more'); ?></a></span>-->
                                                        <!-- Split button -->
                                                        <span class="btn-group dropup">
                                                            <button type="button" class="btn btn-success font-13"><a class="no-decoration white" href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>"><?php echo $this->translator->translator('property_front_page_property_more'); ?></a></button>
                                                            <button type="button" class="btn btn-success dropdown-toggle font-13" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                <span class="caret"></span>
                                                                <span class="sr-only">Toggle Dropdown</span>
                                                            </button>
                                                            <ul class="dropdown-menu dropdown-menu-right font-13">
                                                                <li><a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'emails', 'action' => 'friend', 'property_title' => $this->escape($entry['property_title']), 'form_id' => $this->translator->translator('email_to_friend_form_id')), 'Email-To-Friend/:property_title/:form_id', true); ?>"><?php echo $this->translator->translator('property_front_page_property_email_friend'); ?></a></li>
                                                                <?php
                                                                if (!empty($this->group_datas['review_id'])) {
                                                                    $review_no = $review_helper->getNumOfReviews($entry['id'], $this->escape($this->group_datas['review_id']));
                                                                    ?>
                                                                    <li>
                                                                        <a href="<?php echo $this->url(array('module' => 'Review', 'controller' => 'frontend', 'action' => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $entry['id']), 'Review-Write/:group_id/:item_id', true); ?>">
                                                                            <?php echo $this->translator->translator('common_write_review'); ?>
                                                                        </a>
                                                                    </li>
                                                                <?php } ?>
                                                                <li role="separator" class="divider"></li>
                                                                <li><a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title']), 'tab' => 2), 'Property-details/:property_title/:tab', true); ?>"><?php echo $this->translator->translator('property_front_page_property_fpan'); ?></a></li>
                                                                <li><a href="<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->escape($entry['property_title']), 'tab' => 1), 'Property-details/:property_title/:tab', true); ?>"><?php echo $this->translator->translator('property_front_page_property_photo'); ?></a></li>
                                                            </ul>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <?php
                        } else {
                            //echo "Match not found";
                        }
                    }
                }
                ?>
            </tbody>
        </table>
        <div id="bottomPagination">
            <?php
            echo $this->paginationControl($this->view_datas, 'Sliding', 'frontend/agents-pagination-flickr.phtml');
            ?>
        </div>
        <?php
    } else {
        ?>
        <div class="col-md-12 products-price">
            <p class="margin-top-4 font-weight-normal black-light"><?php echo $this->translator->translator('member_only_view_agency_member'); ?></p>
            <div class="pull-center margin-top-bottom-8">
            <a class="btn btn-success margin-right-4" href="Register"><?php echo $this->translator->translator('member_only_register'); ?></a>
            <a class="btn btn-success" href="Frontend-Login"><?php echo $this->translator->translator('login'); ?></a>
            </div>
        </div>

        <?php
    }
    ?>
    <script>
        $('article').readmore({
            moreLink: '<a href="#">[Lihat semua]</a>',
            lessLink: '<a href="#">[Tutup]</a>',
            collapsedHeight: 72,
            speed: 500
        });
    </script>
</div>