<?php 
$host = $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
$serverName = $_SERVER['SERVER_NAME'];
$requestUri = $_SERVER['REQUEST_URI'];
$exceptions = array('index.php', 'Beranda');
$slash = '/';
$frontend = 'http://www.pembantu.com';
$conflict = false;
$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
?>
<footer id="footer">
    <div class="container">
<?php
foreach ($exceptions as $exception) {
       if (false !== strpos($slash, $requestUri) || false !== strpos($host, $exception)){
          $conflict = true;
          break;
      }
    }
if ($conflict){ ?>
        <div class="block-ad-footer">
           <?php echo $this->partial('blocks/ad_footer_noAjax.phtml'); ?>
        </div>
    
        <div class="social">
            <?php echo $this->translator->translator('footer_social','', '', $front_template['theme_folder']); ?><br /><br />
            <a href="https://www.facebook.com/pembantucom" target="_blank"><p class="facebook"></p></a>
            <a href="http://www.twitter.com/pembantucom" target="_blank"><p class="twitter"></p></a>
            <a href="http://www.youtube.com/channel/UCa_JG3o9sGerAT08TO3F_FA" target="_blank"><p class="youtube"></p></a>
            <a href="http://feeds.feedburner.com" target="_blank"><p class="rss"></p></a>
            <a href="https://plus.google.com/100837777019765857881/videos" target="_blank"><p class="gplus"></p></a>
        </div>
<?php }
else { ?>
        <div class="block-ad-footer">
            <?php echo $this->partial('blocks/ad_footer.phtml'); ?>
        </div>
    
        <div class="social">
          <?php echo $this->translator->translator('footer_social','', '', $front_template['theme_folder']); ?><br /><br />
            <a href="https://www.facebook.com/pembantucom" target="_blank"><p class="facebook"></p></a>
            <a href="http://www.twitter.com/pembantucom" target="_blank"><p class="twitter"></p></a>
            <a href="http://www.youtube.com/channel/UCa_JG3o9sGerAT08TO3F_FA" target="_blank"><p class="youtube"></p></a>
            <a href="http://feeds.feedburner.com" target="_blank"><p class="rss"></p></a>
            <a href="https://plus.google.com/100837777019765857881/videos" target="_blank"><p class="gplus"></p></a>
        </div>
    <?php } ?>       
       <div class="links">
    			<span><?php echo $this->translator->translator('footer_link_important','', '', $front_template['theme_folder']); ?></span>
                <ul>
                    <li class="first"><a href="#"><?php echo $this->translator->translator('footer_link_find_property','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="pembantu-rumah-tangga"><?php echo $this->translator->translator('footer_link_sell_property','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="baby-sitter"><?php echo $this->translator->translator('footer_link_buy_property','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="perawat-lansia"><?php echo $this->translator->translator('footer_link_left_property','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="semua-profesi"><?php echo $this->translator->translator('footer_link_latest_property','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="keanggotaan"><?php echo $this->translator->translator('footer_link_keanggotaan','', '', $front_template['theme_folder']); ?></a></li>  
                    <li><a href="tips-artikel"><?php echo $this->translator->translator('footer_link_news','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="FAQ"><?php echo $this->translator->translator('footer_link_list','', '', $front_template['theme_folder']); ?></a></li>    
                </ul>
    	   </div>
            <div class="links">
            	<span><?php echo $this->translator->translator('footer_link_quick','', '', $front_template['theme_folder']); ?></span> 
                <ul>
                    <li class="first"><a href="peta-situs"><?php echo $this->translator->translator('footer_link_sitemap','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="testimoni"><?php echo $this->translator->translator('footer_link_feedback','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="syarat-dan-ketentuan"><?php echo $this->translator->translator('footer_link_terms','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="kebijakan-privasi"><?php echo $this->translator->translator('footer_link_privacy','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="tentang-kami"><?php echo $this->translator->translator('footer_link_about','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a href="hubungi-kami"><?php echo $this->translator->translator('footer_link_contact','', '', $front_template['theme_folder']); ?></a></li>
                </ul>
            </div>

       <div class="copyright">
                <?php echo $this->translator->translator('footer_copyright','', '', $front_template['theme_folder']); ?> <?php echo date("Y"); ?> <?php echo $this->translator->translator('footer_all_rights','', '', $front_template['theme_folder']); ?> &nbsp;<?php echo $this->translator->translator('footer_develop_by','', '', $front_template['theme_folder']); ?>           
                     
        </div>
    </div>
    
</footer>