<!DOCTYPE html>
<?php $front_template = Zend_Registry::get('front_template'); $is_frontend = new Eicra_Model_DbTable_Frontend(); $license = new Zend_Session_Namespace('License'); $validation_data = $license->license_data;
$locale = Eicra_Global_Variable::getSession()->sess_lang;
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$auth = Zend_Auth::getInstance ();
   if ($auth->hasIdentity ())
	{
		$globalIdentity = $auth->getIdentity ();
		$role_id = $globalIdentity->role_id;			
		$role = $globalIdentity->role_name;
	}	
?> 
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>
<meta http-equiv="Content-Type" charset=utf-8" />
<link href='https://plus.google.com/114560483743619758934' rel='author'/>
<meta name="google-site-verification" content="T2HMk4pF0EAJecImO7Yv4JrWjnSpqYPlzuuYFg34ghM" />
<meta name="msvalidate.01" content="94908A20686155650CAADF391465B722" />
<meta name="geo.region" content="ID-JR" />
<meta name="geo.placename" content="Bekasi" />
<meta name="geo.position" content="-6.233333;107" />
<meta name="ICBM" content="-6.233333, 107" />
<meta property="og:type" content="product"/>
<meta property="og:site_name" content="pembantu.com"/>
<meta property="fb:app_id" content="184724101550452"/>
<meta name="generator" content="Zend Framework" />
<meta name="robots" content="index, follow" />
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/" /> 
<?php  echo $this->headMeta(); ?>
<?php echo html_entity_decode($this->headTitle(), ENT_QUOTES ,"UTF-8"); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
$version = new Eicra_License_Version();
echo $this->partial('head/headscript.phtml');
$auth = Zend_Auth::getInstance ();
$frontController = Zend_Controller_Front::getInstance();
$moduleName = strtolower($frontController->getRequest()->getModuleName());	
$controllerName = strtolower($frontController->getRequest()->getControllerName());
$actionName = strtolower($frontController->getRequest()->getActionName());
$acount_link = ($auth->hasIdentity ()) ? 'Dashboard' : 'Frontend-Login';
$mem_db = new Members_Model_DbTable_MemberList();
$auth = Zend_Auth::getInstance ();
$hasIdentity = $auth->hasIdentity ();
$cdnExt = 'http://static.busana.com/pembantu/';
$add_url = ($auth->hasIdentity ()) ? $this->url(array('module'=> 'Property','controller'=>'Backendpro', 'action'=>'add'), 'adminrout', true)  : $this->serverUrl().$this->baseUrl().'/Frontend-Login';
?>

<link rel="shortcut icon" href="<?php echo $cdnExt; ?>favicon.ico" />
</head> 
<body>
<div class="wrapper">
	<div id="top-bar">    	
        <div class="container">
            <div class="user-link">
                <span class="welcome">
                  <?php
                	if ($hasIdentity)
                	{
              	?>
                  <?php echo $this->translator->translator('header_welcome','', '', $front_template['theme_folder']).' '.$globalIdentity->firstName.' '.$globalIdentity->lastName; ?>
                  <?php
                }
                 else
                 {
              	?>
                  <?php echo $this->translator->translator('header_welcome_to','', '', $front_template['theme_folder']).' '.$global_conf['site_name']; ?>
                  <?php
                }
              	?>
                  <?php
                	if ($hasIdentity)
                	{
              	?>
                  | <a href="Frontend-Login"><?php echo $this->translator->translator('header_signout','', '', $front_template['theme_folder']); ?></a>
                  <?php
                }
                 else
                 {
              	?>  
                  | <a href="Frontend-Login"><?php echo $this->translator->translator('header_signin','', '', $front_template['theme_folder']); ?></a>
                   <?php
                }
              	?>
                  <?php
                	if ($hasIdentity)
                	{
              	?>
                  <!--| <a href="Registration/104"><?php echo $this->translator->translator('header_register','', '', $front_template['theme_folder']); ?></a>-->
                <?php
                }
                 else
                 {
              	?> 
                  | <a href="Registration/104"><?php echo $this->translator->translator('header_register','', '', $front_template['theme_folder']); ?></a>
                  <?php
                }
              	?>
               
               </span>
            </div>
                
            <div class="quick-access">
                
        
                <div class="top-links">
                    <ul>
                      <?php
                	if ($hasIdentity)
                	{
              	?>
                        <li class="account"><a href="Members/index/profile"><?php echo $this->translator->translator('header_account','', '', $front_template['theme_folder']); ?></a></li>
                      <?php
                }
              	?>  
                      <?php
                	if ($hasIdentity)
                	{
              	?>
                        <li class="first"><a href="Property/backendpro/saved"><?php echo $this->translator->translator('short_list','', '', $front_template['theme_folder']); ?></a></li>
                      <?php
                }
              	?>  
                      <?php
                	if ($hasIdentity)
                	{
              	?>
                      <!--<li class="first"><a href="Sign-In"><?php echo $this->translator->translator('header_logout','', '', $front_template['theme_folder']); ?></a></li>-->
                       <?php
                }
                 else
                 {
              	?>  
                   <li class="first"><a href="Sign-In"><?php echo $this->translator->translator('header_login','', '', $front_template['theme_folder']); ?></a></li>
                      <?php
                }
              	?> 
                      <?php
                	if ($hasIdentity)
                	{
                  ?>
                      <!--<li><a href="Registration/107"><?php echo $this->translator->translator('header_agent_registration','', '', $front_template['theme_folder']); ?></a></li>-->
                      <?php
                }
                 else
                 {
              	?> 
                      <li><a href="Registration/107"><?php echo $this->translator->translator('header_agent_registration','', '', $front_template['theme_folder']); ?></a></li>
                      <?php
                }
              	?> 
                   
                      <li><a href="testimoni"><?php echo $this->translator->translator('header_feedback','', '', $front_template['theme_folder']); ?></a></li>
                        <li><a href="peta-situs"><?php echo $this->translator->translator('header_sitemap','', '', $front_template['theme_folder']); ?></a></li>
                        <!--<li><a href="Contact-Us"><?php //echo $this->translator->translator('header_contact','', '', $front_template['theme_folder']); ?></a></li>-->
                    </ul>
                 </div>
            </div>       
        </div>
	</div>
	<?php echo $this->layout()->render('header'); ?>
	<div id="main-container">
        <nav class="top-nav">
			<?php echo $this->partial('blocks/menu_header.phtml'); ?>
        </nav>
        <?php  
			if($is_frontend->isFrontend()) 
			{
		?> 
        <div id="banner">
        	<div class="left-bg"></div>
        	<div class="bg">
				<?php echo $this->partial('blocks/property_home_banner_search.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_banner_agentSearch.phtml'); ?>
               	<?php echo $this->partial('blocks/ad_home_banner.phtml'); ?>
        	</div>
        	<div class="right-bg"></div>
        </div>
        <?php
			}
		?>
        <section id="main">
            <?php  
                if($is_frontend->isFrontend()) 
                {
            ?> 
            <article id="content">	
                    <div id="usual1" class="usual">
                        <ul>
                          <li><a class="selected" href="#tab1"><?php echo $this->translator->translator('tab_commercial_title','', '', $front_template['theme_folder']); ?></a></li>
                          <li><a class="" href="#tab2"><?php echo $this->translator->translator('tab_residential_title','', '', $front_template['theme_folder']); ?></a></li>
                          <li><a class="" href="#tab6"><?php echo $this->translator->translator('tab_pending_title','', '', $front_template['theme_folder']); ?></a></li>

                        </ul>
                    </div>
                    <div class="usual-content">
                        <div style="display:block;" id="tab1"><?php echo $this->partial('blocks/property_home_content_commercial.phtml'); ?></div>
                        <div style="display: none;" id="tab2"><?php echo $this->partial('blocks/property_home_content_residential.phtml'); ?></div>           
                        <div style="display: none;" id="tab6"><?php echo $this->partial('blocks/property_home_content_pending.phtml'); ?></div>
                    </div>    
                <script type="text/javascript">
                $("#usual1 ul").idTabs();
                </script>                
                <?php echo $this->partial('blocks/property_home_content_featured.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_content_state.phtml'); ?>
                <!--<?php echo $this->partial('blocks/property_home_content_region.phtml'); ?>-->
            </article>
            <aside id="sidebar">
                <!--<?php echo $this->partial('blocks/gallery_home_sidebar_featured.phtml'); ?>-->
                <?php echo $this->partial('blocks/property_home_sidebar_recent.phtml'); ?>
                <?php echo $this->partial('blocks/news_sidebar_latest.phtml'); ?>
            </aside>
            <?php
                }
                else
                {
                    $body_content_class = '';
                    if(!empty($moduleName) && $actionName != 'home')
                    {
                        switch($moduleName)
                        {
                            case 'property':
                                $body_content_class = 'content-inner';
            ?>	
                <div id="sidebar-inner">
                    <?php echo $this->partial('blocks/block_advance_search.phtml'); ?>
                    <?php echo $this->partial('blocks/ad_inner_leftsidebar.phtml'); ?>
                </div>	
            <?php
                        break;
                    }
                }
            ?>
                <div id="<?php echo $body_content_class; ?>"> 
                    <?php echo $this->layout()->content; ?>
                </div>				
            <?php
                }
            ?> 
        </section>
	</div>
	<?php echo $this->layout()->render('footer'); ?>
</div>
</body>
</html>
<?php echo $this->escape($global_conf['analytics_code']); ?>