<?php
//Create variable stack from top, do not replace this
$css_state_refence = '';
$css_state_doctor = '';
$css_state_police = '';
$css_state_age = '';
$css_state_experience = '';
$css_style_experience = '';
if (strpos($property_ref_letter, 'tersedia') !== false) {
    $css_state_refence = 'green-light';
} else {
    $css_state_refence = 'grey';
}
if (strpos($property_doc_letter, 'sehat') !== false) {
    $css_state_doctor = 'green-light';
} else {
    $css_state_doctor = 'grey';
}
if (strpos($property_police_letter, 'baik') !== false) {
    $css_state_police = 'green-light';
} else {
    $css_state_police = 'grey';
}
switch (!empty($getPropertyExperience)) {
    case ($getPropertyExperience <= 5):
        $css_state_experience = $getPropertyExperience * 20;
        $css_style_experience = 'success';
        break;
    case ($getPropertyExperience >= 6 && $getPropertyExperience <= 10):
        $css_state_experience = $getPropertyExperience * 10;
        $css_style_experience = 'warning';
        break;
    case ($getPropertyExperience >= 11 && $getPropertyExperience <= 20):
        $css_state_experience = $getPropertyExperience * 5;
        $css_style_experience = 'danger';
        break;
    case ($getPropertyExperience >= 20 && $getPropertyExperience <= 30):
        $css_state_experience = $getPropertyExperience * 3.33;
        $css_style_experience = 'danger';
        break;
    default :
        $css_state_experience = $getPropertyExperience;
        $css_style_experience = 'primary';
}
switch ($getPropertyAge) {
    case ($getPropertyAge <= 20):
        $css_state_age = 'green-light';
        break;
    case ($getPropertyAge >= 21 && $getPropertyAge <= 30):
        $css_state_age = 'violet';
        break;
    case ($getPropertyAge >= 31 && $getPropertyAge <= 40);
        $css_state_age = 'yellow';
        break;
    case ($getPropertyAge >= 41 && $getPropertyAge <= 50);
        $css_state_age = 'red-light';
        break;
    case ($getPropertyAge >= 51 && $getPropertyAge <= 60);
        $css_state_age = 'red-dark';
        break;
    default :
        $css_state_age = 'grey';
}
//echo $css_state_refence;
//echo $css_state_doctor;
//echo $css_state_police;
//echo $css_state_age;
//echo $css_state_experience;
//echo $css_style_experience;
?>

