<div role="tabpanel" class="tab-pane fade active in" id="container-3_details" aria-labelledby="home-tab">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"><i class="fa fa-search-plus margin-right-4"></i><?php echo $getPropertySkillsLabel; ?></div>
                <ul class="list-group">
                    <?php
                    if (!empty($property_skills_arr[0])) {
                        foreach ($property_skills_arr as $skill => $skill_name) {
                            echo '
                                    <li class="list-group-item"><span class="badge icon-placeholder">
                                    <i class="fa fa-check-square-o green-light"></i>
                                    </span>' . $this->escape($skill_name) . '</li>';
                        }
                    }
                    ?>
                </ul>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $getPropertyAvailToWorkInLabel; ?></div>
                <ul>
                    <?php                    
                    if (!empty($property_available_to_work_in[0])) {
                        foreach ($property_available_to_work_in as $place => $place_name) {
                            echo '
                                    <li class="list-group-item"><span class="badge icon-placeholder">
                                    <i class="fa fa-check-square-o green-light"></i>
                                    </span>' . $this->escape($place_name) . '</li>';
                        }
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>