<div class="row">
    <ul>
        <?php
        if ($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' )) {
            $width_img = 'width="70"';
        } else {
            $width_img = '';
        }
        if ($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' )) {
            $height_img = 'height="80px"';
        } else {
            $height_img = '';
        }
        $img_arr = explode(',', $this->view_datas['property_image']);
        $i = 1;
        foreach ($img_arr as $key => $value) {
            ?>
            <li>
                <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/property/property_image/<?php echo $value; ?>" width="140" height="150" title="<?php echo $this->escape($this->propertyForm->property_name->getValue()); ?>"><img src="http://static.busana.com/pembantu/loading.gif" data-src="data/frontImages/property/property_image/<?php echo $value; ?>" <?php echo $width_img . ' ' . $height_img; ?> border="0" class="lazyTab thumb additional-thumb"/></a>
            </li>
            <?php
            $i++;
        }
        ?> 
    </ul>
</div>