<?php
$front_template = Zend_Registry::get('front_template');
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$license = new Zend_Session_Namespace('License');
$validation_data = $license->license_data;
?>
<span class="col-sm-12">
    <ul>
        <!--<li><a href="semua-profesi"><?php echo $this->translator->translator('footer_link_latest_property', '', '', $front_template['theme_folder']); ?></a></li>-->
        <li><a href="tips-artikel"><?php echo $this->translator->translator('footer_link_news', '', '', $front_template['theme_folder']); ?></a></li>
        <li><a href="FAQ"><?php echo $this->translator->translator('footer_link_list', '', '', $front_template['theme_folder']); ?></a></li>
        <li><a href="syarat-dan-ketentuan"><?php echo $this->translator->translator('footer_link_terms', '', '', $front_template['theme_folder']); ?></a></li>
        <li><a href="kebijakan-privasi"><?php echo $this->translator->translator('footer_link_privacy', '', '', $front_template['theme_folder']); ?></a></li>
        <li><a href="tentang-kami"><?php echo $this->translator->translator('footer_link_about', '', '', $front_template['theme_folder']); ?></a></li>
        <li><a href="hubungi-kami"><?php echo $this->translator->translator('footer_link_contact', '', '', $front_template['theme_folder']); ?></a></li>

    </ul>
</span>