<?php
$front_template = Zend_Registry::get('front_template');
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$license = new Zend_Session_Namespace('License');
$validation_data = $license->license_data;
$detect = new Mobile_Detect;
$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
$scriptVersion = $detect->getScriptVersion();
?>
<footer id="footer">
    <div class="top-row"> 
        <div class="container">
            <div class="row">
                <?php if ($detect->isMobile() && !$detect->version('iPad') && !$detect->isTablet()) { ?>
                    <div class="col-md-12">
                        <?php echo $this->partial('mobile/blocks/footer/contents/short-links.phtml'); ?>
                    </div>  
                <?php } else { ?>               
                    <div class="col-md-6">
                        <?php echo $this->partial('blocks/news/news_latest.phtml'); ?>
                    </div>
                    <div class="col-md-6">                    
                        <?php echo $this->partial('blocks/footer/contents/short-links.phtml'); ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="bottom-row">
        <div class="container">
            <div class="col-md-8 copyright">
                <?php echo $this->translator->translator('footer_copyright', '', '', $front_template['theme_folder']); ?> <?php echo date("Y"); ?> <?php echo $this->translator->translator('footer_all_rights', '', '', $front_template['theme_folder']); ?> &nbsp;
                <?php echo $this->translator->translator('footer_develop_by', '', '', $front_template['theme_folder']); ?>


            </div>

            <div class="col-md-4">
                <div class="social">
                    <a href="https://www.facebook.com/pembantucom" target="_blank"><i class="fa fa-facebook-square fa-2x blue-facebook"></i></a>
                    <a href="http://www.twitter.com/pembantucom" target="_blank"><i class="fa fa-twitter-square fa-2x blue-twitter"></i></a>
                    <a href="https://plus.google.com/100837777019765857881/videos" target="_blank"><i class="fa fa-google-plus-square fa-2x red-google"></i></a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" charset="utf-8">
        jQuery(document).ready(function () {
            jQuery("img.lazyTab").lazy({combined: true, delay: 32000});
            jQuery("img.lazy").lazy({delay: 8000});
            jQuery("li.lazy").lazy({delay: 16000});
        });
    </script>
</footer>
