<?php
$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance ();
$acount_link = 'Members/index/profile' ;
$my_account_link	=	($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">'.$this->translator->translator('header_account','', '', $front_template['theme_folder']).'|'.'</a>' : '<a href="">'.'</a>';
$sugnIn_link	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_signout','', '', $front_template['theme_folder']).'</a>' : '<a href="Frontend-Login">'.$this->translator->translator('header_signin','', '', $front_template['theme_folder']).'</a>';
$sugnIn_link_agency	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_logout','', '', $front_template['theme_folder']).'</a>' : '<a href="Sign-In">'.$this->translator->translator('header_login','', '', $front_template['theme_folder']).'</a>';
$add_url =  $this->baseUrl().'Frontend-Login';
$devider = ' |';
$detect = new Mobile_Detect;
$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
$scriptVersion = $detect->getScriptVersion();
?>
<header>
    <?php
    if ($detect->isMobile() && !$detect->version('iPad') && !$detect->isTablet()) {
//        echo $this->partial('blocks/topbar/top_bar.phtml');
        echo $this->partial('mobile/blocks/topbar/top_bar.phtml');
    }else{
//        echo $this->partial('mobile/blocks/topbar/top_bar.phtml');
        echo $this->partial('blocks/topbar/top_bar.phtml');
    }
    ?>
</header>