<?php
$license = new Zend_Session_Namespace('License');
$validation_data = $license->license_data;
$global_conf = Zend_Registry::get('global_conf');
?>
<div id="footer">
	<p class="powered"><br />
    <?php echo $this->translator->translator('common_footer_copy_right'); ?><?php echo date("Y"); ?> <?php echo $this->translator->translator('common_footer_all_right'); ?></p>
    
    <p class="version"><?php echo $this->translator->translator('common_vesrion_label'); ?> <?php echo Eicra_License_Version::getVersion(); ?></p>
</div>