<?php

class property_search_box {

    protected $_group = 1;
    protected $_limit = 12;
    protected $_role_id = 107;
    protected $_DBconn;
    protected $_front_template;
    protected $_view;
    protected $_business_type_db;
    protected $_currency;
    protected $_cat_Info;
    protected $_mem_db;
    protected $_country_db;
    protected $translator;
    protected $postValue;
    protected $_global_conf;

    public function __construct($view) {
        $this->_front_template = Zend_Registry::get('front_template');
        $this->_view = $view;

        //DB Connection
        $this->_DBconn = Zend_Registry::get('msqli_connection');
        $this->_DBconn->getConnection();

        $this->translator = Zend_Registry::get('translator');

        $frontController = Zend_Controller_Front::getInstance();

        //DD Class
        $this->_global_conf = Zend_Registry::get('global_conf');
        $this->_currency = new Zend_Currency($this->_global_conf['default_locale']);
        $this->_business_type_db = new Property_Model_DbTable_BusinessType();
        $this->_cat_Info = new Property_Model_DbTable_Category();
        $this->_mem_db = new Members_Model_DbTable_MemberList();
        $this->_country_db = new Property_Model_DbTable_Country();
        $this->postValue = $frontController->getRequest()->getPost();
    }

    public function truncate($phrase, $start_words, $max_words) {
        $phrase_array = explode(' ', $phrase);
        if (count($phrase_array) > $max_words && $max_words > 0)
            $phrase = implode(' ', array_slice($phrase_array, $start_words, $max_words)) . '...';
        return $phrase;
    }

    public function class_body() {
        $version = Zend_Registry::get('version');
        $translator = Zend_Registry::get('translator');
        $property_db = new Property_Model_DbTable_Properties();
        $state_DB = new Property_Model_DbTable_State();
        $country_info = $this->_country_db->getCountryName($this->_global_conf['default_country']);
        $property_front_page_agent_id = $translator->translator('property_front_page_agent_id', '', 'Property');
        $property_front_page_agent_id_arr = explode(',', $property_front_page_agent_id);
        $auth = Zend_Auth::getInstance();
        $hasIdentity = $auth->hasIdentity();

        //$min_feature_room_no = $property_db->getBorderItems('feature_room_no', 'ASC');
        //$max_feature_room_no = $property_db->getBorderItems('feature_room_no', 'DESC');
//		$min_feature_bathroom = $property_db->getBorderItems('feature_bathroom', 'ASC');
//		$max_feature_bathroom = $property_db->getBorderItems('feature_bathroom', 'DESC');
        $select = $this->_DBconn->select()
                ->from(array('up' => Zend_Registry::get('dbPrefix') . 'user_profile'), array('up.user_id', 'title' => 'up.title', 'firstName' => 'up.firstName', 'lastName' => 'up.lastName', 'companyName' => 'up.companyName', 'address' => 'up.address', 'phone' => 'up.phone', 'mobile' => 'up.mobile', 'fax' => 'up.fax'))
                ->where('up.role_id = ?', $this->_role_id)
                ->where('up.status = ?', '1')
                ->group('up.user_id')
                ->limit($this->limit)
                ->joinLeft(array('pp' => Zend_Registry::get('dbPrefix') . 'property_page'), 'pp.property_owner = up.user_id', array('property_num' => 'COUNT(*)'));
        $mem_data = $select->query()->fetchAll();
        echo $this->_view->headScript()->setFile('application/layouts/scripts/' . $this->_front_template['theme_folder'] . '/vendor/scripts/js/jquery.switchButton.js');
//        echo $this->_view->headLink()->setStylesheet('application/layouts/scripts/' . $this->_front_template['theme_folder'] . '/css/jquery.switchButton.css');
        ?>
        <script type="text/javascript">
            $(function () {
                $('a.searchButton').click(function () {
                    $('#propertySearchBox').submit();
                });
            });
        </script>

        <script type="text/javascript">
            $(function () {
                $("#property_owner_box").combobox();
                autoSuggestion('property_name_box', "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'searchname'), 'adminrout', true) ?>", {'property_name': ''}, ['property_primary_image', 'property_image', 'property_name', 'property_name', 'owner_name', 'property_room', 'property_location', 'state_name'], 'data/frontImages/property/property_image', 2);
                autoSuggestion('post_code_box', "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'searchname'), 'adminrout', true) ?>", {'post_code': ''}, ['property_primary_image', 'property_image', 'property_name', 'post_code', 'owner_name', 'property_postcode', 'property_location'], 'data/frontImages/property/property_image', 2);
                autoSuggestion('property_price_box', "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'searchname'), 'adminrout', true) ?>", {'property_price': ''}, ['property_primary_image', 'property_image', 'property_name', 'price', 'owner_name', 'property_price', 'property_location'], 'data/frontImages/property/property_image', 2);
                autoSuggestion('area_id_block', "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'city'), 'adminrout', true) ?>", {'city': '', 'limit': '10', 'order': 'ASC', 'order_sort': 'city'}, ['city_id', 'city_id', 'city', 'city_value'], '', 1);

            });

            $(document).ready(function () {
                $('#off-label').hide();
                function stripslashes(str)
                {
                    str = str.replace(/\\'/g, '\'');
                    str = str.replace(/\\"/g, '"');
                    str = str.replace(/\\0/g, '\0');
                    str = str.replace(/\\\\/g, '\\');
                    return str;
                }
                $('select.country_id_box').change(function () {
                    if ($('select.country_id_box option:selected').val() == 'any' || $('select.country_id_box option:selected').val() == '')
                    {
                        $('select.area_id_box').html('<option value="any"><?php echo $this->translator->translator("common_select_area"); ?></option>');
                        $('select.state_id_box').html('<option value="any"><?php echo $this->translator->translator("common_select_state"); ?></option>');
                    }
                    else
                    {
                        $.ajax({
                            url: "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'states'), 'adminrout', true) ?>",
                            type: 'POST',
                            data: {id: $('select.country_id_box option:selected').val()},
                            beforeSend: function () {
                                $('select.state_id_box').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
                                $('select.area_id_box').html('<option value="any"><?php echo $this->translator->translator("common_select_area"); ?></option>');
                                $('#state_id_box_err').html('<img src="application/layouts/scripts/<?php echo $this->_front_template['theme_folder']; ?>/images/loader/search.gif" border="0"/>');
                            },
                            success: function (response) {
                                //alert(response);
                                var json_arr = eval("(" + response + ")");
                                var option = '<option value="any"><?php echo $this->translator->translator("common_select_state"); ?></option>';
                                if (json_arr.status == 'ok')
                                {
                                    for (var i = 0; i < json_arr.states.length; i++)
                                    {
                                        option += '<option value="' + json_arr.states[i].state_id + '" >' + stripslashes(json_arr.states[i].state_name) + '</option>';
                                    }
                                    $('select.state_id_box').html(option);
                                }
                                else
                                {
                                    $('select.state_id_box').html('<option value="any">' + json_arr.msg + '</option>');
                                }
                                $('#state_id_box_err').html('');
                            }
                        });
                    }
                });

                $('select.state_id_box').change(function () {

                    if ($('select.state_id_box option:selected').val() == 'any' || $('select.state_id_box option:selected').val() == '')
                    {
                        $('select.area_id_box').html('<option value="any"><?php echo $this->translator->translator("common_select_area"); ?></option>');
                    }
                    else
                    {
                        $.ajax({
                            url: "<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'areas'), 'adminrout', true) ?>",
                            type: 'POST',
                            data: {id: $('select.state_id_box option:selected').val()},
                            beforeSend: function () {
                                $('select.area_id_box').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
                                $('#area_id_box_err').html('<img src="application/layouts/scripts/<?php echo $this->_front_template['theme_folder']; ?>/images/loader/search.gif" border="0" />');
                            },
                            success: function (response) {
                                //alert(response);
                                var json_arr = eval("(" + response + ")");
                                var option = '<option value="any"><?php echo $this->translator->translator("common_select_area"); ?></option>';
                                if (json_arr.status == 'ok')
                                {
                                    for (var i = 0; i < json_arr.cities.length; i++)
                                    {
                                        option += '<option value="' + json_arr.cities[i].city_id + '" >' + stripslashes(json_arr.cities[i].city) + '</option>';
                                    }
                                    $('select.area_id_box').html(option);
                                }
                                else
                                {
                                    $('select.area_id_box').html('<option value="any">' + json_arr.msg + '</option>');
                                }
                                $('#area_id_box_err').html('');
                            }
                        });
                    }
                });
            });

        </script>

        <script>
            $(function () {
                $("#slider-1.demo input").switchButton({
                    width: 80,
                    height: 20,
                    button_width: 35,
                    on_label: "<?php echo $this->translator->translator('block_search_on_label_mobile', '', '', $this->_front_template['theme_folder']); ?>",
                    off_label: "<?php echo $this->translator->translator('block_search_off_label_mobile', '', '', $this->_front_template['theme_folder']); ?>"
                });
            })
        </script>
        <!--<div class="panel panel-default no-border margin-top-20">-->
        <div>
            <div class="container-fluid">
                <h4 class="navbar pull-right margin-top-4 panel-title" data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch">
                    <a class="white bold no-decoration" data-toggle="collapse" href="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch">
                        <div class="input-group">
                            <input type="text" class="form-control" id="disabledInput" placeholder="Mencari pembantu..." disabled>
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button"><i class="fa fa-search grey"></i></button>
                            </span>
                        </div>
                    </a>
                </h4>
            </div>
            <div id="collapseSearch" class="panel-collapse collapse">
                <div class="panel-body padding-right-left-15">
                    <div class="block-search padding-right-left-bottom-10">
                        <!--<i class="fa fa-search fa-3x search"></i><h2><?php echo $this->translator->translator('block_search_title', '', '', $this->_front_template['theme_folder']); ?></h2>-->
                        <!--<span class="slogan"><?php echo $this->translator->translator('block_search_slogan', $this->_view->escape($country_info['value']), '', $this->_front_template['theme_folder']); ?></span>-->
                        <hr>

                        <center>
                            <div class="slider demo" id="slider-1">
                                <input style="display: none;" value="1" checked="checked" type="checkbox">
                            </div>
                        </center>
                        <hr>
                        <span id="on-label-span">
                            <form action="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'search', 'action' => 'items'), 'Search-Items', true); ?>" method="post" name="propertySearchBox" id="propertySearchBox" role="form">
                                <div class="row row1">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="feature_other_amenities"><?php echo $this->translator->translator('block_search_other_amenities', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <select name="feature_other_amenities_LIKE" id="feature_other_amenities" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="jakarta"><?php echo $this->translator->translator('block_search_jakarta', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="surabaya"><?php echo $this->translator->translator('block_search_surabaya', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="medan"><?php echo $this->translator->translator('block_search_medan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bandung"><?php echo $this->translator->translator('block_search_bandung', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="semarang"><?php echo $this->translator->translator('block_search_semarang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="ambon"><?php echo $this->translator->translator('block_search_ambon', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="balikpapan"><?php echo $this->translator->translator('block_search_balikpapan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="banda aceh"><?php echo $this->translator->translator('block_search_bandaaceh', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bandar lampung"><?php echo $this->translator->translator('block_search_bandarlampung', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="banjar"><?php echo $this->translator->translator('block_search_banjar', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="banjar baru"><?php echo $this->translator->translator('block_search_banjarbaru', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="banjarmasin"><?php echo $this->translator->translator('block_search_banjarmasin', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="batam"><?php echo $this->translator->translator('block_search_batam', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="batu"><?php echo $this->translator->translator('block_search_batu', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="baubau"><?php echo $this->translator->translator('block_search_baubau', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bekasi"><?php echo $this->translator->translator('block_search_bekasi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bengkulu"><?php echo $this->translator->translator('block_search_bengkulu', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bima"><?php echo $this->translator->translator('block_search_bima', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="binjai"><?php echo $this->translator->translator('block_search_binjai', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bitung"><?php echo $this->translator->translator('block_search_bitung', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="blitar"><?php echo $this->translator->translator('block_search_blitar', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bogor"><?php echo $this->translator->translator('block_search_bogor', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bontang"><?php echo $this->translator->translator('block_search_bontang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="bukittinggi"><?php echo $this->translator->translator('block_search_bukittinggi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="cilegon"><?php echo $this->translator->translator('block_search_cilegon', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="cimahi"><?php echo $this->translator->translator('block_search_cimahi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="cirebon"><?php echo $this->translator->translator('block_search_cirebon', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="denpasar"><?php echo $this->translator->translator('block_search_denpasar', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="depok"><?php echo $this->translator->translator('block_search_depok', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="dumai"><?php echo $this->translator->translator('block_search_dumai', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="gorontalo"><?php echo $this->translator->translator('block_search_gorontalo', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="gunung sitoli"><?php echo $this->translator->translator('block_search_gunungsitoli', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="jambi"><?php echo $this->translator->translator('block_search_jambi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="jayapura"><?php echo $this->translator->translator('block_search_jayapura', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kediri"><?php echo $this->translator->translator('block_search_kediri', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kendari"><?php echo $this->translator->translator('block_search_kendari', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kota klaten"><?php echo $this->translator->translator('block_search_kotaklaten', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kotamobagu"><?php echo $this->translator->translator('block_search_kotamobagu', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kupang"><?php echo $this->translator->translator('block_search_kupang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="langsa"><?php echo $this->translator->translator('block_search_langsa', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lhokseumawe"><?php echo $this->translator->translator('block_search_lhokseumawe', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lubuklinggau"><?php echo $this->translator->translator('block_search_lubuklinggau', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="madiun"><?php echo $this->translator->translator('block_search_madiun', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="magelang"><?php echo $this->translator->translator('block_search_magelang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="makassar"><?php echo $this->translator->translator('block_search_makassar', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="malang"><?php echo $this->translator->translator('block_search_malang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="manado"><?php echo $this->translator->translator('block_search_manado', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="mataram"><?php echo $this->translator->translator('block_search_mataram', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="metro"><?php echo $this->translator->translator('block_search_metro', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="mojokerto"><?php echo $this->translator->translator('block_search_mojokerto', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="padang"><?php echo $this->translator->translator('block_search_padang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="padang sidempuan"><?php echo $this->translator->translator('block_search_padangsidempuan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pagaralam"><?php echo $this->translator->translator('block_search_pagaralam', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="palangkaraya"><?php echo $this->translator->translator('block_search_palangkaraya', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="palembang"><?php echo $this->translator->translator('block_search_palembang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="palopo"><?php echo $this->translator->translator('block_search_palopo', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="palu"><?php echo $this->translator->translator('block_search_palu', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pangkalpinang"><?php echo $this->translator->translator('block_search_pangkalpinang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="parepare"><?php echo $this->translator->translator('block_search_parepare', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pasuruan"><?php echo $this->translator->translator('block_search_pasuruan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="payakumbuh"><?php echo $this->translator->translator('block_search_payakumbuh', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pakalongan"><?php echo $this->translator->translator('block_search_pakalongan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pekanbaru"><?php echo $this->translator->translator('block_search_pekanbaru', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pematangsiantar"><?php echo $this->translator->translator('block_search_pematangsiantar', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="pontianak"><?php echo $this->translator->translator('block_search_pontianak', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="prabumulih"><?php echo $this->translator->translator('block_search_prabumulih', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="probolinggo"><?php echo $this->translator->translator('block_search_probolinggo', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="purwokerto"><?php echo $this->translator->translator('block_search_purwokerto', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="salatiga"><?php echo $this->translator->translator('block_search_salatiga', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="samarinda"><?php echo $this->translator->translator('block_search_samarinda', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="serang"><?php echo $this->translator->translator('block_search_serang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="singkawang"><?php echo $this->translator->translator('block_search_singkawang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="sorong"><?php echo $this->translator->translator('block_search_sorong', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="sukabumi"><?php echo $this->translator->translator('block_search_sukabumi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="surakarta"><?php echo $this->translator->translator('block_search_surakarta', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tangerang"><?php echo $this->translator->translator('block_search_tangerang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tangerang selatan"><?php echo $this->translator->translator('block_search_tangerangselatan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tanjungbalai"><?php echo $this->translator->translator('block_search_tanjungbalai', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tanjungpinang"><?php echo $this->translator->translator('block_search_tanjungpinang', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tarakan"><?php echo $this->translator->translator('block_search_tarakan', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tasikmalaya"><?php echo $this->translator->translator('block_search_tasikmalaya', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tebingtinggi"><?php echo $this->translator->translator('block_search_tebingtinggi', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tegal"><?php echo $this->translator->translator('block_search_tegal', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="ternate"><?php echo $this->translator->translator('block_search_ternate', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="yogyakarta"><?php echo $this->translator->translator('block_search_yogyakarta', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="luar_negeri"><?php echo $this->translator->translator('block_search_overseas', '', '', $this->_front_template['theme_folder']); ?></option>

                                            </select>
                                        </div>
                                    </div>
                                    <!--property_owner_box/Penyalur-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="property_owner_box"><?php echo $this->translator->translator('block_search_owner', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <span class="ui-widget clearfix">
                                                <select name="property_owner_=" id="property_owner_box-new" class="form-control">
                                                    <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                    <?php
                                                    if (!empty($mem_data) && $hasIdentity) {
                                                        foreach ($mem_data as $entry) {
                                                            $selected = (!empty($this->postValue['property_owner_=']) && $this->postValue['property_owner_='] == $key) ? ' selected="selected" ' : '';
                                                            ?>
                                                            <option value="<?php echo $this->_view->escape($entry['user_id']); ?>"<?php echo $selected; ?><?php echo $selected; ?>><?php echo $this->_view->escape($entry['companyName']); ?></option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </select>
                                            </span>
                                        </div>
                                    </div>
                                    <!--/property_owner_box/Penyalur-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="property_type_box"><?php echo $this->translator->translator('block_search_type', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <?php $type_info = $this->_business_type_db->getOptions(null, 'business_type', 'ASC'); ?>
                                            <select name="property_type_=" id="property_type_box" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <?php
                                                if ($type_info) {
                                                    foreach ($type_info as $info) {
                                                        $selected = (!empty($this->postValue['property_type_=']) && $this->postValue['property_type_='] == $info['id']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $info['id']; ?>"<?php echo $selected; ?>><?php echo $this->_view->escape($info['business_type']); ?></option>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>                
                                    <!--                  <div class="col-md-2">
                                                        <label for="property_price_box"><?php echo $this->translator->translator('block_search_price', '', '', $this->_front_template['theme_folder']); ?> <?php echo $currency = $this->_currency->getSymbol(); ?></label>
                                                        <input name="property_price_>=" id="property_price_box" placeholder="<?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?>" value="<?php
                                    if (!empty($this->postValue['property_price_>='])) {
                                        echo $this->postValue['property_price_>='];
                                    }
                                    ?>" type="text" class="form-control" />
                                                        
                                                    </div>-->

                                    <!--category_id/Kategori-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="category_id_box"><?php echo $this->translator->translator('block_search_category', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <?php $cat_data = $this->_cat_Info->getOptions(null, 'category_name', 'ASC', '1'); ?>
                                            <select name="category_id_=" id="category_id_box" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <?php
                                                if ($cat_data) {
                                                    foreach ($cat_data as $info) {
                                                        $selected = (!empty($this->postValue['category_id_=']) && $this->postValue['category_id_='] == $info['id']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $info['id']; ?>"<?php echo $selected; ?>><?php echo $this->_view->escape($info['category_name']); ?></option>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/category_id/Kategori-->
                                    <!--property_price-gte/Gaji Bulanan Min-->
                                    <div class="col-md-2">
                                        <label for="property_price-gte"><?php echo $this->translator->translator('block_search_price_min', '', '', $this->_front_template['theme_folder']); ?></label>
                                        <?php $min_price_arr = $property_db->getPrice('ASC'); ?>
                                        <select name="property_price_>=" id="property_price-gte" class="form-control">
                                            <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                            <?php
                                            if ($min_price_arr) {
                                                foreach ($min_price_arr as $key => $value) {
                                                    if (!empty($value['property_price'])) {
                                                        $selected = (!empty($this->postValue['property_price_>=']) && $this->postValue['property_price_>='] == $value['property_price']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $value['property_price']; ?>"<?php echo $selected; ?>><?php echo $currency . ' ' . $this->_view->escape($value['property_price']); ?></option>
                                                        <?php
                                                    }
                                                }
                                            }
                                            ?>
                                        </select> 
                                    </div>
                                    <!--/property_price-gte/Gaji Bulanan Min-->
                                </div>
                                <div class="row row2">
                                    <!--property_price-lte/Gaji Bulanan Max-->
                                    <div class="col-md-2">
                                        <label for="property_price-lte"><?php echo $this->translator->translator('block_search_price_max', '', '', $this->_front_template['theme_folder']); ?></label>
                                        <?php $max_price_arr = $property_db->getPrice('DESC'); ?>
                                        <select name="property_price_<=" id="property_price-lte" class="form-control">
                                            <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                            <?php
                                            if ($max_price_arr) {
                                                foreach ($max_price_arr as $key => $value) {
                                                    if (!empty($value['property_price'])) {
                                                        $selected = (!empty($this->postValue['property_price-lte']) && $this->postValue['property_price_<='] == $value['property_price_<=']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $value['property_price']; ?>"<?php echo $selected; ?>><?php echo $currency . ' ' . $this->_view->escape($value['property_price']); ?></option>
                                                        <?php
                                                    }
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <!--/property_price-lte/Gaji Bulanan Max-->
                                    <!--feature_glazing/Pendidikan Terakhir-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="feature_glazing"><?php echo $this->translator->translator('block_search_glazing', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <select name="feature_glazing_=" id="feature_glazing" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="tidak_sekolah"><?php echo $this->translator->translator('block_search_glazing_no_school', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="sd"><?php echo $this->translator->translator('block_search_glazing_sd', '', '', $this->_front_template['theme_folder']); ?></option>                              
                                                <option value="smp"><?php echo $this->translator->translator('block_search_glazing_smp', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="sma"><?php echo $this->translator->translator('block_search_glazing_sma', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="Perguruan_Tinggi"><?php echo $this->translator->translator('block_search_glazing_sarjana', '', '', $this->_front_template['theme_folder']); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/feature_glazing/Pendidikan Terakhir-->

                                    <!--feature_other_amenities/Kota Anda-->

                                    <!--/feature_other_amenities/Kota Anda-->



                                    <!--house_name/Status-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="house_name"><?php echo $this->translator->translator('block_search_house_name', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <select name="house_name_=" id="house_name" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lajang"><?php echo $this->translator->translator('block_search_status_single', '', '', $this->_front_template['theme_folder']); ?></option>                              
                                                <option value="menikah"><?php echo $this->translator->translator('block_search_status_married', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="Janda/Duda"><?php echo $this->translator->translator('block_search_status_widowed', '', '', $this->_front_template['theme_folder']); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/house_name/Status-->

                                    <!--Tipology/Agama-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="property_tipology"><?php echo $this->translator->translator('block_search_tipology', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <select name="property_tipology_=" id="property_tipology" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="islam"><?php echo $this->translator->translator('block_search_tipology_muslim', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="budha"><?php echo $this->translator->translator('block_search_tipology_buddhist', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="katolik"><?php echo $this->translator->translator('block_search_tipology_catholic', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="kristen"><?php echo $this->translator->translator('block_search_tipology_christian', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="hindu"><?php echo $this->translator->translator('block_search_tipology_hindu', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lainnya"><?php echo $this->translator->translator('block_search_tipology_other', '', '', $this->_front_template['theme_folder']); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/Tipology/Agama-->
                                    <!--feature_dinning_space/Suku Asal-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="feature_dinning_space"><?php echo $this->translator->translator('block_search_dinning_space', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <select name="feature_dinning_space_=" id="feature_dinning_space" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="jawa"><?php echo $this->translator->translator('block_search_dinning_javanese', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="sunda"><?php echo $this->translator->translator('block_search_dinning_sundanese', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="banten"><?php echo $this->translator->translator('block_search_dinning_padangnese', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="NTT"><?php echo $this->translator->translator('block_search_dinning_chinese', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lampung"><?php echo $this->translator->translator('block_search_dinning_batak', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="madura"><?php echo $this->translator->translator('block_search_dinning_madurese', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="melayu"><?php echo $this->translator->translator('block_search_dinning_malay', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <option value="lainnya"><?php echo $this->translator->translator('block_search_dinning_other', '', '', $this->_front_template['theme_folder']); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/feature_dinning_space/Suku Asal-->
                                    <!--feature_bathroom_min/Usia Min-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="feature_bathroom_min"><?php echo $this->translator->translator('block_search_bathroom_min', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <?php $bathroom = $property_db->getNumberOfBathRooms('ASC'); ?>
                                            <select name="feature_bathroom_>=" id="feature_bathroom" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <?php
                                                foreach ($bathroom as $key => $value) {
                                                    if (!empty($value['feature_bathroom'])) {
                                                        $selected = (!empty($this->postValue['feature_bathroom_>=']) && $this->postValue['feature_bathroom_>='] == $value['feature_bathroom']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $value['feature_bathroom']; ?>"<?php echo $selected; ?>><?php echo $this->_view->escape($value['feature_bathroom']); ?></option>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <!--feature_bathroom_min/Usia Min-->
                                </div>

                                <div class="row row3">


                                    <!--                  <div class="col-md-4">
                                                        <label for="country_id_box"><?php echo $this->translator->translator('block_search_country', '', '', $this->_front_template['theme_folder']); ?></label>
                                    <?php $country_data = $this->_country_db->getCountryInfo(); ?>
                                                        <select name="country_id" id="country_id_box" class="country_id_box form-control">
                                                            <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                    <?php
                                    if ($country_data) {
                                        $selected_country_id = (empty($this->postValue['country_id'])) ? $this->_global_conf['default_country'] : $this->postValue['country_id'];
                                        foreach ($country_data as $key => $value) {
                                            $selected = ($selected_country_id == $key) ? ' selected="selected" ' : '';
                                            ?>
                                                                                                                                                                                    <option value="<?php echo $key; ?>"<?php echo $selected; ?>><?php echo $this->_view->escape($value); ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                                        </select>
                                                    </div>-->

                                    <!--                  <div class="col-md-2">
                                                        <label for="state_id_box"><?php echo $this->translator->translator('block_search_state', '', '', $this->_front_template['theme_folder']); ?><span id="state_id_box_err"></span></label>
                                                        <select name="state_id" id="state_id_box" class="state_id_box state form-control">
                                                            <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                    <?php
                                    $state_info = $state_DB->getAllStateInfo($selected_country_id);
                                    foreach ($state_info as $key => $value) {
                                        $selected = ($value['state_id'] == $this->postValue['state_id']) ? ' selected="selected" ' : '';
                                        echo '<option value="' . $this->_view->escape($value['state_id']) . '"' . $selected . '>' . $this->_view->escape($value['state_name']) . '</option>';
                                    }
                                    ?>	
                                                        </select>
                                                    </div>-->
                                    <!--
                                                    
                                                   <div class="col-md-2">
                                                        <label for="area_id_box"><?php echo $this->translator->translator('block_search_area', '', '', $this->_front_template['theme_folder']); ?> &nbsp; <span id="area_id_box_err"></span></label>
                                                        <select name="area_id" id="area_id_box" class="area_id_box form-control">
                                                            <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                        </select>
                                                    </div>
                                                </div>
                                                
                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <div class="form-group">
                                                            <label for="feature_room_no"><?php echo $this->translator->translator('block_search_room', '', '', $this->_front_template['theme_folder']); ?></label>
                                                            <select name="feature_room_no-gte" id="feature_room_no" class="form-control">
                                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                    <?php
                                    for ($i = $min_feature_room_no; $i <= $max_feature_room_no; $i++) {
                                        $selected = (!empty($this->postValue['feature_room_no-gte']) && $this->postValue['feature_room_no-gte'] == $i) ? ' selected="selected" ' : '';
                                        ?>
                                                                                                                            <option value="<?php echo $i; ?>"<?php echo $selected; ?>><?php echo $i; ?></option>
                                        <?php
                                    }
                                    ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                    -->                

                                    <!--Bathroom/??-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="feature_bathroom"><?php echo $this->translator->translator('block_search_bathroom_max', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <?php $bathroom = $property_db->getNumberOfBathRooms('DESC'); ?>
                                            <select name="feature_bathroom_<=" id="feature_bathroom" class="form-control">
                                                <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                <?php
                                                foreach ($bathroom as $key => $value) {
                                                    if (!empty($value['feature_bathroom'])) {
                                                        $selected = (!empty($this->postValue['feature_bathroom_<=']) && $this->postValue['feature_bathroom_<='] == $value['feature_bathroom']) ? ' selected="selected" ' : '';
                                                        ?>
                                                        <option value="<?php echo $value['feature_bathroom']; ?>"<?php echo $selected; ?>><?php echo $this->_view->escape($value['feature_bathroom']); ?></option>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <!--/Bathroom/??-->
                                    <!--Mark Template-->
                                    <!--                        <div class="col-md-2">
                                                                <div class="form-group">
                                                                    <label for=""></label>
                                                                    <select name="" id="" class="form-control">
                                                                    <option value="any"><?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?></option>
                                                                    <option></option>
                                                                    </select>
                                                                </div>
                                                            </div>-->
                                    <!--/Template-->
                                    <!--property_name/Nama Pembantu-->
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="property_name_box"><?php echo $this->translator->translator('block_search_name', '', '', $this->_front_template['theme_folder']); ?></label>
                                            <input type="hidden" name="block_search" value="search" />
                                            <input name="property_name_LIKE" id="property_name_box" type="text" class="form-control" placeholder="<?php echo $this->translator->translator('block_search_any', '', '', $this->_front_template['theme_folder']); ?>" value="<?php
                                            if (!empty($this->postValue['property_name_LIKE'])) {
                                                echo $this->postValue['property_name_LIKE'];
                                            }
                                            ?>" />

                                        </div>
                                    </div>
                                    <!--/property_name/Nama Pembantu-->
                                    <div class="col-md-3">
                                        <div class="clr form-button-container pull-center">
                                            <span class="btn btn-success ui-widget-content-1"><a href="javascript:void(0);" class="white searchButton"><span class="icon search"><?php echo $this->translator->translator('block_search_btn', '', '', $this->_front_template['theme_folder']); ?></span></a></span>
                                        </div>                    
                                    </div>
                                </div>
                            </form>
                        </span>

                        <span id="off-label-span">
                            <div class="row">
                                <div class="col-md-6 margin-top-bottom-8">
                                    <div class="pull-center">
                                    <form action="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'Frontend', 'action' => 'owners'), 'Property-Agent-Search', true) ?>" method="post" name="propertySearchBox" id="propertySearchBox" role="form">
                                                <!--<label for="role_id_block"><?php echo $this->translator->translator('block_agent_search_label', '', '', $this->_front_template['theme_folder']); ?></label><br>-->
                                                <?php
                                                if ($property_front_page_agent_id_arr) {
                                                    foreach ($property_front_page_agent_id_arr as $property_front_page_agent_id_key => $agents) {
                                                        $agent_arr = explode(';;', $agents);
                                                        $checked = ($property_front_page_agent_id_key == '0') ? 'checked="checked"' : '';
                                                        ?>
                                                        <input type="radio" class="hidden" name="role_id" id="role_id_block" <?php echo $checked; ?> value="<?php echo $agent_arr[0]; ?>"/><?php // echo $agent_arr[1];  ?>
                                                        <?php
                                                    }
                                                }
                                                ?>                                       
                                            <input type="submit" name="Submit" value="<?php echo $this->translator->translator('block_search_agency_btn', '', '', $this->_front_template['theme_folder']); ?>" class="btn btn-success btn-lg"/>                                       
                                    </form>
                                    </div>
                                </div>
                                <div class="col-md-6 margin-top-bottom-8">
                                    <div class="pull-center">
                                    <form action="<?php echo $this->baseUrl; ?>daftar-penyalur-pembantu">
                                        <input type="submit" value="<?php echo $this->translator->translator('block_search_agency_non_member_btn', '', '', $this->_front_template['theme_folder']); ?>" class="btn btn-success btn-lg">
                                    </form>
                                    </div>
                                </div>
                            </div>                  
                        </span>
                    </div>
                </div>
            </div>
        </div>



        <?php
    }

}

try {
    $property_search_box_class = new property_search_box($this);
    $property_search_box_class->class_body();
} catch (Exception $e) {
    echo $e->getMessage();
}
?>