<div class="block">
    <?php

    class pending_property {

        protected $_group = 1;
        protected $_limit = 9;
        protected $_category_id = 9;
        protected $_DBconn;
        protected $_front_template;
        protected $_view;
        protected $_currency;
        protected $_group_db;
        protected $translator;
        protected $_business_type_db;

        public function __construct($view) {
            $this->_front_template = Zend_Registry::get('front_template');
            $this->_view = $view;

            //DB Connection
            $this->_DBconn = Zend_Registry::get('msqli_connection');
            $this->_DBconn->getConnection();
            $this->_business_type_db = new Property_Model_DbTable_BusinessType();
            $this->translator = Zend_Registry::get('translator');

            //DD Class
            $global_conf = Zend_Registry::get('global_conf');
            $this->_currency = new Zend_Currency($global_conf['default_locale']);
            $this->_group_db = new Property_Model_DbTable_PropertyGroup();
        }

        public function truncate($phrase, $start_words, $max_words) {
            $phrase_array = explode(' ', $phrase);
            if (count($phrase_array) > $max_words && $max_words > 0)
                $phrase = implode(' ', array_slice($phrase_array, $start_words, $max_words)) . '...';
            return $phrase;
        }

        public function normalize_ucw($phrase) {
            $set_to_lower = strtolower($phrase);
            $phrase = ucwords($set_to_lower);
            return $phrase;
        }

        public function normalize_ucf($phrase) {
            $set_to_lower = strtolower($phrase);
            $phrase = ucfirst($set_to_lower);
            return $phrase;
        }

        public function text_limiter($phrase, $start_words, $max_words) {
            if (strlen($phrase) > $max_words) {
                $phrase = substr($phrase, $start_words, $max_words) . '...';
            }
            return $phrase;
        }

        public function class_body() {
            $groupInfo = $this->_group_db->getGroupName($this->_group);
            $curSymbol = $this->_currency->getSymbol();
            $select = $this->_DBconn->select()
                    ->from(array('pp' => Zend_Registry::get('dbPrefix') . 'property_page'), array('*'))
                    ->where('pp.active = ?', '1')
                    //->where('pp.featured = ?', '1')
                    ->where('pp.group_id = ?', $this->_group)
                    ->where('pp.category_id = ?', $this->_category_id)
                    ->order("pp." . $groupInfo['latest_file_sort'] . " " . $groupInfo['latest_file_order'])
                    ->joinLeft(array('pc' => Zend_Registry::get('dbPrefix') . 'property_category'), 'pp.category_id = pc.id', array('category_name' => 'pc.category_name', 'category_title' => 'pc.category_title'))
                    ->joinLeft(array('ct' => Zend_Registry::get('dbPrefix') . 'cities'), 'pp.area_id = ct.city_id', array('city' => 'ct.city'))
                    ->joinLeft(array('st' => Zend_Registry::get('dbPrefix') . 'states'), 'pp.state_id = st.state_id', array('state_name' => 'st.state_name'))
                    ->limit($this->_limit);
            $property_info = $select->query()->fetchAll();
            $maximum_stars_digit = $this->translator->translator('maximum_stars_digit', '', 'Property');
            $cdnExt = 'http://static.busana.com/';

            if ($property_info) {
                foreach ($property_info as $entry) {
                    $property_image_val_arr = explode(',', $entry['property_image']);
                    $property_image_no = (!empty($property_image_val_arr[0])) ? count($property_image_val_arr) : '0';
                    if ($this->_view->escape($entry['property_primary_image'])) {
                        $thumb_image = 'data/frontImages/property/property_image/' . $this->_view->escape($entry['property_primary_image']);
                    } else {
                        if ($this->_view->escape($entry['property_image'])) {
                            $thumb_image = 'data/frontImages/property/property_image/' . $this->_view->escape($property_image_val_arr[0]);
                        } else {
                            $thumb_image = 'application/layouts/scripts/' . $this->_front_template['theme_folder'] . '/images/mod_property_img/no_image.png';
                        }
                    }
                    $type_info = $this->_business_type_db->getBusinessTypeInfo($entry['property_type']);
                    $curSymbol = $this->_currency->getSymbol();
                    $getPropertyName = $this->_view->escape($entry['property_name']);
                    $setPropertyName = $this->text_limiter($getPropertyName, 0, 14);
                    $property_name = $this->normalize_ucw($setPropertyName);
                    $getPropertyPrice = $this->_view->escape($entry['property_price']);
                    $setPropertyPrice = $this->text_limiter($getPropertyPrice, 0, 8);
                    $propertyPrice = $curSymbol . ' ' . number_format($setPropertyPrice, 0, ',', '.');
                    $getPropertyLocation = $this->_view->escape($entry['state_name']);
                    $setPropertyLocation = $this->text_limiter($getPropertyLocation, 0, 11);
                    $property_location = ucwords($setPropertyLocation);
                    $strip_seperator = " - ";
                    $getPropertyShortDesc = $this->_view->escape(strip_tags($entry['property_desc']));
                    $setPropertyShortDesc = $this->text_limiter($getPropertyShortDesc, 0, 85);
//                    $short_desc = $this->truncate($getPropertyShortDesc, 0, 10);
                    $short_desc = $this->normalize_ucf($setPropertyShortDesc);
                    ?>           
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <h6>
                                    <a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->_view->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>" title="<?php echo $this->_view->escape($entry['property_name']); ?>" link="" class="preview">
                                        <?php echo $property_name; ?>
                                    </a>
                                </h6>
                                <span class="location"><?php echo $strip_seperator; ?><a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->_view->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>"><?php echo $property_location; ?></a></span><br>
                                <figure>
                                    <a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->_view->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>" link="<?php echo $thumb_image; ?>"  title="<?php echo $this->_view->escape($entry['property_name']); ?>" width="250" class="preview"><img class="lazy" src="<?php echo $cdnExt; ?>pembantu/loading.gif" data-src="<?php echo $thumb_image; ?>" width="150" height="199"/></a>
                                    <div class="type"><?php
                                        if ($type_info && $type_info['business_type']) {
                                            echo $this->_view->escape($type_info['business_type']);
                                        }
                                        ?></div>
                                    <div class="photo-count-container">
                                        <div class="photo-count"><a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->_view->escape($entry['property_title']), 'tab' => '1'), 'Property-details/:property_title/:tab', true); ?>"><span class="fa fa-camera"></span> <?php echo $this->translator->translator('property_front_page_property_photo_no', $property_image_no, 'Property'); ?></a></div>
                                    </div>
                                </figure>

                                <div class="details">
                                    <span class="price"><?php echo $propertyPrice; ?></span>
                                    <div class="ratings">
                                        <?php
                                        for ($i = 1; $i < $maximum_stars_digit; $i++) {
                                            $property_stars = ($i <= $this->_view->escape($entry['stars'])) ? "<i class='fa fa-star orange-light'></i>" : "<i class='fa fa-star-o grey-dark'></i>";
                                            echo $property_stars . '&nbsp;';
                                        }
                                        ?>
                                    </div>
                                    <p class="short_desc_tab"><?php echo ucfirst($short_desc); ?></p>
                                    <a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'details', 'property_title' => $this->_view->escape($entry['property_title'])), 'Property-details/:property_title', true); ?>" class="btn btn-success btn-xs"><?php echo $this->translator->translator('block_details_link', '', '', $this->_front_template['theme_folder']); ?></a>
                                </div>  
                            </div>

                            <div class="panel-footer">
                <!--                <span>
                                    <i class="property-icon icon-area"></i> <?php echo $this->_view->escape($entry['property_size']); ?> <?php echo $this->translator->translator('block_search_size_unit', '', '', $this->_front_template['theme_folder']); ?>
                                </span>-->
                                <span>
                                    <?php echo (int) $this->_view->escape($entry['feature_room_no']); ?> <?php echo $this->translator->translator('partial_featured_property_room'); ?>
                                </span>
                                <span class="no-b-bdr no-r-bdr">
                                    <?php echo (int) $this->_view->escape($entry['feature_bathroom']); ?> <?php echo $this->translator->translator('partial_featured_property_bathroom'); ?>
                                </span>

                                                                                <!--                <span class="no-b-bdr no-r-bdr">
                                                                                    <i class="property-icon icon-garage"></i> <?php echo (int) $this->_view->escape($entry['feature_garage']); ?> <?php echo $this->translator->translator('partial_featured_property_garage', '', '', $this->_front_template['theme_folder']); ?>
                                                                                </span>-->
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="btn btn-sm btn-default"><a href="<?php echo $this->_view->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'category', 'category_id' => $this->_view->escape($entry['category_id'])), 'Category-List/:category_id', true); ?>"><?php echo $this->translator->translator('block_tab_more', $this->_view->escape($entry['category_name']), '', $this->_front_template['theme_folder']); ?></a></div>
                    <?php
                }
            }

        }

        try {
            $rural_property_class = new pending_property($this);
            $rural_property_class->class_body();
        } catch (Exception $e) {
            echo $e->getMessage();
        }
        ?>
</div>