<script type="text/javascript">

    $(document).ready(function () {

        /****************************Sorting Table Start*********************/
        var oTable = $("#sortTable").dataTable({
            "bPaginate": true,
            "aLengthMenu": [10, 25, 50, 100],
            "sPaginationType": "full_numbers",
            "bDestroy": true,
            "bLengthChange": true,
            "bSearchable": true,
            "bFilter": false,
            "bSort": false,
            "bInfo": false,
            "bAutoWidth": true,
            "bProcessing": false,
            "bSortClasses": true,
            "bStateSave": false,
            "bServerSide": false,
            "aaSorting": [[0, "asc"]],
            "aoColumnDefs": [
                {"bSortable": false, "bSortClasses": false, "aTargets": [0]}
            ],
            "oLanguage": {"sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>"}
        });

        /****************************Sorting Table End*********************/
        $('input.search_btn').click(function () {
            var self = this;
            var formData = getFormData();

            $.ajax({
                url: "<?php echo $this->url(array('module' => 'Property', 'controller' => 'frontend', 'action' => 'search'), 'adminrout', true) ?>",
                type: 'POST',
                data: formData,
                beforeSend: function () {
                    $('#loader_img').html('<img src="images/ajax_loader7.gif" width="12" height="12" border="0" />');
                },
                success: function (response)
                {
                    //alert(response);
                    var json_arr = eval("(" + response + ")");
                    if (json_arr.status == 'ok')
                    {
                        putSearchResult(oTable, json_arr.search_data);
                    }
                    else
                    {
                        oTable.fnClearTable();
                        //openMsgDialog(json_arr.msg);
                    }
                    $('#loader_img').html('');
                }
            });
        });
    });

</script>