<?php
$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance ();
$acount_link = 'Members/index/profile' ;
$my_account_link	=	($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">'.$this->translator->translator('header_account','', '', $front_template['theme_folder']).'|'.'</a>' : '<a href="">'.'</a>';
$sugnIn_link	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_signout','', '', $front_template['theme_folder']).'</a>' : '<a href="Frontend-Login">'.$this->translator->translator('header_signin','', '', $front_template['theme_folder']).'</a>';
$sugnIn_link_agency	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_logout','', '', $front_template['theme_folder']).'</a>' : '<a href="Sign-In">'.$this->translator->translator('header_login','', '', $front_template['theme_folder']).'</a>';
$add_url =  $this->baseUrl().'Frontend-Login';
$devider = ' |';
$tab_title_recent_title = $this->translator->translator('block_recent_title', '', '', $front_template['theme_folder']);
$tab_title_immediately_available = $this->translator->translator('tab_commercial_title', '', '', $front_template['theme_folder']);
$tab_title_already_available = $this->translator->translator('tab_residential_title', '', '', $front_template['theme_folder']);
$tab_title_inval = $this->translator->translator('tab_pending_title', '', '', $front_template['theme_folder']);
?>
<div class="row">
    <div class="col-md-12">
        <!-- Featured Tab Start-->	
        <div id="usual1" class="usual">
            <ul>
                <li><a class="selected" href="#tab1"><?php echo strtoupper($tab_title_recent_title); ?></a></li>
                <li><a class="" href="#tab2"><?php echo strtoupper($tab_title_immediately_available); ?></a></li>
                <li><a class="" href="#tab3"><?php echo strtoupper($tab_title_already_available); ?></a></li>
                <li><a class="" href="#tab4"><?php echo strtoupper($tab_title_inval); ?></a></li>
                <!--<li><a class="" href="#tab4"><?php echo $this->translator->translator('tab_land_title', '', '', $front_template['theme_folder']); ?></a></li>-->
                <!--<li><a class="" href="#tab5"><?php echo $this->translator->translator('tab_rent_title', '', '', $front_template['theme_folder']); ?></a></li>-->
                <!--<li><a class="" href="#tab6"><?php echo $this->translator->translator('tab_rural_title', '', '', $front_template['theme_folder']); ?></a></li>-->
            </ul>
        </div>
        <div class="usual-content">
            <div style="display:block;" id="tab1"><?php echo $this->partial('blocks/showcase/contents/property_home_content_recent.phtml'); ?></div>
            <div style="display:none;" id="tab2"><?php echo $this->partial('blocks/showcase/contents/property_home_content_commercial.phtml'); ?></div>
            <div style="display: none;" id="tab3"><?php echo $this->partial('blocks/showcase/contents/property_home_content_residential.phtml'); ?></div>
            <div style="display: none;" id="tab4"><?php echo $this->partial('blocks/showcase/contents/property_home_content_pending.phtml'); ?></div>
            <!--<div style="display: none;" id="tab4"><?php // echo $this->partial('blocks/property_home_content_land.phtml');         ?></div>-->
            <!--<div style="display: none;" id="tab5"><?php // echo $this->partial('blocks/property_home_content_rent.phtml');         ?></div>-->
            <!--<div style="display: none;" id="tab6"><?php // echo $this->partial('blocks/property_home_content_rural.phtml');         ?></div>-->
        </div>

        <script type="text/javascript">
            $("#usual1 ul").idTabs();
        </script>
        <!-- Featured Tab End-->
    </div>

</div>