<?php 

$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance ();
$acount_link = 'Members/index/profile' ;
$my_account_link	=	($auth->hasIdentity()) ? '<a href="Members/index/profile" class="topbar_logout_btn">'.$this->translator->translator('header_account','', '', $front_template['theme_folder']).'|'.'</a>' : '<a href="">'.'</a>';
$sugnIn_link	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_signout','', '', $front_template['theme_folder']).'</a>' : '<a href="Frontend-Login">'.$this->translator->translator('header_signin','', '', $front_template['theme_folder']).'</a>';
$sugnIn_link_agency	=	($auth->hasIdentity()) ? '<a href="javascript:void(0);" class="topbar_logout_btn">'.$this->translator->translator('header_logout','', '', $front_template['theme_folder']).'</a>' : '<a href="Sign-In">'.$this->translator->translator('header_login','', '', $front_template['theme_folder']).'</a>';
$add_url =  $this->baseUrl().'Frontend-Login';
$add_maid_link = ($auth->hasIdentity()) ? '<a href="Property/backendpro/add" class="topbar_logout_btn">'.$this->translator->translator('Member_frontend_add_your_maid_now','', '', $front_template['theme_folder']).'</a>' : '<a href="Registration/104">'.$this->translator->translator('header_register','', '', $front_template['theme_folder']).'</a>';
$devider = ' |';
$site_name = $global_conf['site_name'];
?>

<script type="text/javascript">
$(document).ready(function() {	
	logOut('a.topbar_logout_btn', '<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/ajax-loader-email.gif" />', '', '<?php echo $this->translator->translator('common_front_header_signin','', '', $front_template['theme_folder']); ?>');
});
</script>
<div id="top-bar" class="">
    	<div class="container">
        	<div class="row">
            	<div class="col-md-12 user-link">
                	<?php echo $this->translator->translator('header_welcome','', '', $front_template['theme_folder']); ?> | <?php echo $sugnIn_link; ?> | <?php echo $add_maid_link ?>
                </div>
           	</div>
        </div>
    </div>

<!--    	<div class="container">
        	<div class="row">
            	 <div class="col-md-12">
                     <div class="logo no-float">
                         <a href="#"><img class="img-responsive pull-center" src="<?php if($global_conf['frontend_header_logo']){ echo $global_conf['frontend_header_logo']; }else{ ?>application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/logo-site.png<?php } ?>" alt="<?php echo $this->escape($global_conf['site_title']); ?>" title="<?php echo $this->escape($global_conf['site_title']); ?>" border="0"></a>
                    </div>
                 </div>
            </div>
        </div>-->