<!DOCTYPE html>
<?php $front_template = Zend_Registry::get('front_template'); $is_frontend = new Eicra_Model_DbTable_Frontend(); $license = new Zend_Session_Namespace('License'); $validation_data = $license->license_data;
$locale = Eicra_Global_Variable::getSession()->sess_lang;
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
?> 
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>
<meta charset="utf-8">
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/" /> 
<link rel="shortcut icon" href="<?php $global_conf = Zend_Registry::get('global_conf'); echo $global_conf['frontend_favicon']; ?>" />
<?php  echo $this->headMeta(); ?>
<?php echo html_entity_decode($this->headTitle(), ENT_QUOTES ,"UTF-8"); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
$version = new Eicra_License_Version();
echo $this->partial('head/headscript.phtml');
$auth = Zend_Auth::getInstance ();
$frontController = Zend_Controller_Front::getInstance();
$moduleName = strtolower($frontController->getRequest()->getModuleName());	
$controllerName = strtolower($frontController->getRequest()->getControllerName());
$actionName = strtolower($frontController->getRequest()->getActionName());
?>
</head> 
<body>
	<!-- Header Start -->
	<?php echo $this->layout()->render('header'); ?>
	<!-- Header End -->

	<!-- Top Navigation Start-->
    <nav class="top-nav">
    	<div class="container">
        	<?php echo $this->partial('blocks/menu_header.phtml'); ?>
        </div>
    </nav>
    <!-- Top Navigation End-->
        
	<!-- Main Body Start -->
	<section id="main-container">
        
        <!-- Inner Layout Start -->
        <div id="main">
            <div class="main-container"> 
            	<?php if($moduleName == 'members' || ( $actionName != 'add' && $actionName != 'edit')) : $body_content_style = ''; ?>                       
                <!-- Inner Sidebar Start -->
                <aside id="sidebar-inner">					
                    <?php echo $this->partial('blocks/members/members_menu.phtml');   ?>                  	
                    <?php echo $this->partial('blocks/members/members_sidebar_overview.phtml'); ?>
                    <?php echo $this->partial('blocks/members/ad_sidebar.phtml'); ?>
                </aside>
                <!-- Inner Sidebar End -->
                <?php else: $body_content_style = 'style="width:100%"'; endif; ?> 
                <!-- Inner Content Start -->
                <article id="content-inner" <?php echo $body_content_style; ?>>
                	<?php echo $this->partial('blocks/members/breadcrumb.phtml'); ?>
                  	<?php echo $this->layout()->content ?>
                </article>
                <!-- Inner Content End -->
            </div>
        </div>  
    	<!-- Inner Layout End -->
	</section>
	<!-- Main Body End -->

	<!-- Footer Start -->
	<?php echo $this->layout()->render('footer'); ?>
    <!-- Footer End -->

<div class="go-top"><a href="#top" id="scroll-top"><?php echo $this->translator->translator('footer_top','', '', $front_template['theme_folder']); ?></a></div>
<?php echo $this->headScript()->setFile('application/layouts/scripts/'.$front_template['theme_folder'].'/vendor/scripts/js/scroll.js'); ?>
</body>
</html>
<?php echo $this->escape($global_conf['analytics_code']); ?>