<?php 
?>
<div id="top-bar">    	
    <div class="container">
        <div class="user-link">
            <span class="welcome"><?php echo $this->translator->translator('header_welcome','', '', $front_template['theme_folder']).' '.$global_conf['site_name']; ?> | <?php echo $sugnIn_link; ?> | <a href="Registration/104"><?php echo $this->translator->translator('header_register','', '', $front_template['theme_folder']); ?></a></span>
        </div>
            
        <div class="quick-access">
            <div class="flags">
                
            </div>
    
            <div class="">
                
             </div>
        </div>       
    </div>
</div>