        <div class="col-md-6">
            <div class="panel panel-info">
                <!-- Default panel contents -->
                <div class="panel-heading"><i class="fa fa-search-plus margin-right-4"></i><?php echo $this->translator->translator('property_front_page_Title_detail'); ?></div>

                <!-- Table -->
                <table class="table">
                    <tbody>

                        <?php
                        if ($this->view_datas['category_id']) {
                            $category_info = $cat_Info->getCategoryInfo($this->view_datas['category_id']);
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $this->ProductForm->category_id->getAttrib('font_end_label'); ?></td>
                                <td class="value-table"><?php echo $this->escape($category_info['category_name']); ?></td>
                            </tr>
                            <?php
                        }
                        if ($this->view_datas['property_price']) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_price_nego'); ?></td>
                                <td class="value-table"><?php echo $propertyPrice; ?></td>
                            </tr>
                            <?php
                        }
                        if ($downPayment) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_administration_fee'); ?></td>
                                <td class="value-table"><?php echo $downPayment; ?></td>
                            </tr>
                            <?php
                        }
                        if ($replacement_guarantee) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $this->translator->translator('property_front_page_label_replacement_guarantee'); ?></td>
                                <td class="value-table"><?php echo $replacement_guarantee; ?></td>
                            </tr>
                            <?php
                        }
                        if ($getWorkAlways) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getWorkAlwaysLabel; ?></td>
                                <td class="value-table"><?php echo $work_always; ?></td>
                            </tr> 
                            <?php
                        }
                        if ($getPropertyStatus) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyStatusLabel; ?></td>
                                <td class="value-table"><?php echo ucwords($getPropertyStatus); ?></td>
                            </tr> 
                            <?php
                        }
                        if ($getPropertyHaveChild) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyHaveChildLabel; ?></td>
                                <td class="value-table"><?php echo ucfirst($getPropertyHaveChild); ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyReligion) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyReligionLabel; ?></td>
                                <td class="value-table"><?php echo ucfirst($getPropertyReligion); ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyCurrLocation) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyCurrLocationLabel; ?></td>
                                <td class="value-table"><?php echo ucwords($getPropertyCurrLocation); ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyProv) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyProvLabel; ?></td>
                                <td class="value-table"><?php echo $getPropertyProv; ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyFearDog) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyFearDogLabel; ?></td>
                                <td class="value-table"><?php echo $getPropertyFearDog; ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyWorkOverseas) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyWorkOverseasLabel; ?></td>
                                <td class="value-table"><?php echo ucfirst($getPropertyWorkOverseas); ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertyEnglishSkill) {
                            ?>
                            <tr>
                                <td class="label-table"><?php echo $getPropertyEnglishSkillLabel; ?></td>
                                <td class="value-table"><?php echo ucfirst($getPropertyEnglishSkill); ?></td>
                            </tr>
                            <?php
                        }
                        if ($getPropertySkills) {
                            $property_skills_arr = explode(',', $getPropertySkills);
                            if (!empty($property_skills_arr[0])) {
                                ?>
                                <tr>
                                    <td class="label-table"><?php echo $getPropertySkillsLabel; ?></td>
                                    <td class="value-table">
                                        <ul>
                                            <?php
                                            foreach ($property_skills_arr as $skill => $skill_name) {
                                                echo '<li>' . $skill_name . '</li>';
                                            }
                                            ?>
                                        </ul>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        if ($getPropertyAvailToWorkIn) {
                            $location_willing_to_work_arr = explode(',', $getPropertyAvailToWorkIn);
                            if (!empty($location_willing_to_work_arr[0])) {
                                ?>
                                <tr>
                                    <td class="label-table"><?php echo $getPropertyAvailToWorkInLabel; ?></td>
                                    <td class="value-table">
                                        <ul>
                                            <?php
                                            foreach ($location_willing_to_work_arr as $location => $location_name) {
                                                echo '<li>' . $location_name . '</li>';
                                            }
                                            ?>
                                        </ul>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>
<!--                        <tr>
    <td class="label-table">Label</td>
    <td class="value-table">Value</td>
</tr>-->
                    </tbody>
                </table>
            </div>
        </div>